import { runToolTests } from '../../test-runner.mjs';

// Static contract coverage for capabilities that are intentionally environment
// dependent. These cases ensure every advertised action and new parameter is
// represented in the validation matrix even when Unreal is not running.
await runToolTests('production-contract-coverage', [
  { toolName: 'manage_asset', arguments: { action: 'reference_viewer', assetPath: '/Game/MCPTest/ContractAsset', maxDepth: 2 }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'audit_assets', directory: '/Game/MCPTest', outputPath: 'Saved/contract-asset-audit.json' }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'size_map_analysis', directory: '/Game/MCPTest', outputPath: 'Saved/contract-asset-size-map.json' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'configure_chunking', projectPath: 'ContractProject', generateChunks: true, chunkHardReferencesOnly: true, maxChunkSize: 104857600 }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'configure_plugin_settings', projectPath: 'ContractProject', configName: 'DefaultEngine.ini', section: '/Script/ContractPlugin.ContractSettings', key: 'bEnabled', value: 'True' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'configure_windows_build', projectPath: 'ContractProject', key: 'TargetedRHIs', value: '(D3D_SM6)' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'configure_linux_build', projectPath: 'ContractProject', key: 'TargetedRHIs', value: '(VULKAN_SM6)' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'configure_mac_build', projectPath: 'ContractProject', key: 'TargetedRHIs', value: '(METAL_SM6)' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'configure_ios_build', projectPath: 'ContractProject', key: 'bEnableMetalMRT', value: 'True' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'configure_android_build', projectPath: 'ContractProject', key: 'TargetSDKVersion', value: '34' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'configure_android_signing', projectPath: 'ContractProject', packageName: 'com.contract.game', keyStore: 'Contract.keystore', keyAlias: 'contract', keyStorePassword: 'contract-password', keyPassword: 'contract-key-password' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'configure_ios_signing', projectPath: 'ContractProject', bundleIdentifier: 'com.contract.game', mobileProvision: 'Contract.mobileprovision', signingCertificate: 'iPhone Distribution: Contract' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'take_photo_mode_screenshot', filename: 'ContractPhotoMode.png', mode: 'editor_viewport', includeMetadata: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'save_checkpoint', saveGameObject: '/Game/SaveGames/ContractSaveGame' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'load_checkpoint' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'save_checkpoint_async', saveGameObject: '/Game/SaveGames/ContractSaveGame', slotName: 'AsyncCheckpoint', async: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'load_checkpoint_async', slotName: 'AsyncCheckpoint', async: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'save_game_to_memory', saveGameObject: '/Game/SaveGames/ContractSaveGame' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'load_game_from_memory', dataBase64: 'AQIDBA==' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'save_data_to_slot', slotName: 'RawCheckpoint', dataBase64: 'AQIDBA==' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'load_data_from_slot', slotName: 'RawCheckpoint' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'set_world_rendering', enabled: false }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'set_global_time_dilation', timeDilation: 0.5 }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'set_global_pitch_modulation', pitchModulation: 0.9, timeSec: 0.25 }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'set_force_disable_splitscreen', disableSplitscreen: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'set_game_paused', paused: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'is_game_paused' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'get_audio_time_seconds' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'is_any_local_player_camera_within_range', location: { x: 0, y: 0, z: 0 }, maximumRange: 1000 }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'get_num_local_player_controllers' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'set_subtitles_enabled', enabled: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'are_subtitles_enabled' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'get_active_spatial_plugin' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'set_active_spatial_plugin', pluginName: 'None' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'get_available_spatial_plugins' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'get_platform_name' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'get_accurate_real_time' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'get_time_seconds' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'get_unpaused_time_seconds' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'get_real_time_seconds' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'get_world_delta_seconds' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'get_current_reverb_effect' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'get_player_controller', playerIndex: 0 }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'get_player_pawn', playerIndex: 0 }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'get_player_character', playerIndex: 0 }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'get_player_camera_manager', playerIndex: 0 }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'get_player_state', playerIndex: 0 }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'get_current_level_name', removePrefixString: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'get_viewport_mouse_capture_mode' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'set_viewport_mouse_capture_mode', mouseCaptureMode: 'CaptureDuringMouseDown' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'set_max_audio_channels_scaled', maxChannelCountScale: 0.5 }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'get_max_audio_channel_count' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'are_any_listeners_within_range', location: { x: 0, y: 0, z: 0 }, maximumRange: 1000 }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'get_closest_listener_location', location: { x: 0, y: 0, z: 0 }, maximumRange: 1000, allowAttenuationOverride: false }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'get_game_instance' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'get_game_mode' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'get_game_state' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'get_num_player_controllers' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'get_num_player_states' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'get_targeting_subsystem' }, expected: 'success|error' },
  { toolName: 'control_actor', arguments: { action: 'create_instanced_static_mesh_component', actorName: 'ContractActor', componentName: 'ContractISM', meshPath: '/Engine/BasicShapes/Cube' }, expected: 'success|error' },
  { toolName: 'control_actor', arguments: { action: 'create_checkpoint_actor', actorName: 'ContractCheckpoint' }, expected: 'success|error' },
  { toolName: 'control_actor', arguments: { action: 'create_hierarchical_instanced_static_mesh', actorName: 'ContractActor', componentName: 'ContractHISM', meshPath: '/Engine/BasicShapes/Cube' }, expected: 'success|error' },
  { toolName: 'control_actor', arguments: { action: 'create_procedural_mesh_component', actorName: 'ContractActor', componentName: 'ContractProceduralMesh' }, expected: 'success|error' },
  { toolName: 'manage_geometry', arguments: { action: 'set_mesh_vertices', actorName: 'ContractActor', componentName: 'ContractProceduralMesh', sectionIndex: 0, vertices: [[0, 0, 0], [100, 0, 0], [0, 100, 0]] }, expected: 'success|error' },
  { toolName: 'manage_geometry', arguments: { action: 'set_mesh_normals', actorName: 'ContractActor', componentName: 'ContractProceduralMesh', sectionIndex: 0, normals: [[0, 0, 1], [0, 0, 1], [0, 0, 1]] }, expected: 'success|error' },
  { toolName: 'manage_geometry', arguments: { action: 'set_mesh_uvs', actorName: 'ContractActor', componentName: 'ContractProceduralMesh', sectionIndex: 0, uv0: [[0, 0], [1, 0], [0, 1]] }, expected: 'success|error' },
  { toolName: 'manage_geometry', arguments: { action: 'set_mesh_colors', actorName: 'ContractActor', componentName: 'ContractProceduralMesh', sectionIndex: 0, colors: [[255, 0, 0, 255], [0, 255, 0, 255], [0, 0, 255, 255]] }, expected: 'success|error' },
  { toolName: 'manage_geometry', arguments: { action: 'set_mesh_tangents', actorName: 'ContractActor', componentName: 'ContractProceduralMesh', sectionIndex: 0, tangents: [[1, 0, 0, 0], [1, 0, 0, 0], [1, 0, 0, 0]] }, expected: 'success|error' },
  { toolName: 'manage_geometry', arguments: { action: 'set_mesh_triangles', actorName: 'ContractActor', componentName: 'ContractProceduralMesh', sectionIndex: 0, triangles: [0, 1, 2] }, expected: 'success|error' },
  { toolName: 'manage_geometry', arguments: { action: 'get_mesh_section_bounds', actorName: 'ContractActor', componentName: 'ContractProceduralMesh', sectionIndex: 0 }, expected: 'success|error' },
  { toolName: 'control_actor', arguments: { action: 'spawn_paper_sprite_actor', actorName: 'ContractPaperSprite', paperAssetPath: '/Game/Contract/Sprite' }, expected: 'success|error' },
  { toolName: 'control_actor', arguments: { action: 'spawn_paper_flipbook_actor', actorName: 'ContractPaperFlipbook', paperAssetPath: '/Game/Contract/Flipbook' }, expected: 'success|error' },
  { toolName: 'control_actor', arguments: { action: 'spawn_paper_tile_map_actor', actorName: 'ContractPaperTileMap', paperAssetPath: '/Game/Contract/TileMap' }, expected: 'success|error' },
  { toolName: 'control_actor', arguments: { action: 'set_paper_sprite_color', actorName: 'ContractPaperSprite', color: { r: 1, g: 0.5, b: 0.25, a: 1 } }, expected: 'success|error' },
  { toolName: 'control_actor', arguments: { action: 'set_paper_tile_map_color', actorName: 'ContractPaperTileMap', color: { r: 0.5, g: 0.75, b: 1, a: 1 } }, expected: 'success|error' },
  { toolName: 'control_actor', arguments: { action: 'set_paper_tile_map_layer_color', actorName: 'ContractPaperTileMap', layer: 0, color: { r: 1, g: 0.5, b: 0.25, a: 1 } }, expected: 'success|error' },
  { toolName: 'control_actor', arguments: { action: 'get_paper_tile_map_layer_color', actorName: 'ContractPaperTileMap', layer: 0 }, expected: 'success|error' },
  { toolName: 'control_actor', arguments: { action: 'get_paper_tile_map_info', actorName: 'ContractPaperTileMap' }, expected: 'success|error' },
  { toolName: 'control_actor', arguments: { action: 'get_paper_tile_map_parameters', actorName: 'ContractPaperTileMap' }, expected: 'success|error' },
  { toolName: 'control_actor', arguments: { action: 'get_paper_tile_polygon', actorName: 'ContractPaperTileMap', x: 0, y: 0, layer: 0 }, expected: 'success|error' },
  { toolName: 'control_actor', arguments: { action: 'get_paper_tile', actorName: 'ContractPaperTileMap', x: 0, y: 0, layer: 0, worldSpace: true }, expected: 'success|error' },
  { toolName: 'control_actor', arguments: { action: 'resize_paper_tile_map', actorName: 'ContractPaperTileMap', width: 32, height: 16 }, expected: 'success|error' },
  { toolName: 'control_actor', arguments: { action: 'set_paper_tile_map_default_collision', actorName: 'ContractPaperTileMap', collisionThickness: 10, rebuildCollision: true }, expected: 'success|error' },
  { toolName: 'control_actor', arguments: { action: 'configure_paper_tile_map_layer_collision', actorName: 'ContractPaperTileMap', layer: 0, hasCollision: true, overrideThickness: true, customThickness: 1, overrideOffset: true, customOffset: 0, rebuildCollision: true }, expected: 'success|error' },
  { toolName: 'control_actor', arguments: { action: 'paint_paper_tile', actorName: 'ContractPaperTileMap', x: 0, y: 0, layer: 0, tileIndex: 0, tileSetPath: '/Game/Contract/TileSet', rebuildCollision: true }, expected: 'success|error' },
  { toolName: 'control_actor', arguments: { action: 'fill_paper_tile_region', actorName: 'ContractPaperTileMap', x: 0, y: 0, width: 4, height: 3, layer: 0, tileIndex: 0, tileSetPath: '/Game/Contract/TileSet', rebuildCollision: true }, expected: 'success|error' },
  { toolName: 'control_actor', arguments: { action: 'configure_paper_flipbook', actorName: 'ContractPaperFlipbook', playRate: 1, looping: true, playbackAction: 'play_from_start' }, expected: 'success|error' },
  { toolName: 'control_actor', arguments: { action: 'configure_flipbook_loop', actorName: 'ContractPaperFlipbook', looping: false }, expected: 'success|error' },
  { toolName: 'control_actor', arguments: { action: 'configure_paper_character', actorName: 'ContractPaperCharacter', paperAssetPath: '/Game/Contract/Flipbook', maxWalkSpeed: 600, gravityScale: 1, playbackAction: 'play' }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'create_sprite', name: 'ContractSprite', path: '/Game/Contract', texturePath: '/Game/Contract/Texture', save: true }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'create_flipbook', name: 'ContractFlipbook', path: '/Game/Contract', spritePaths: ['/Game/Contract/SpriteA', '/Game/Contract/SpriteB'], frameRuns: [1, 2], save: true }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'create_tile_set', name: 'ContractTileSet', path: '/Game/Contract', texturePath: '/Game/Contract/Texture', save: true }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'inspect_tile_set', assetPath: '/Game/Contract/TileSet' }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'configure_tile_set', assetPath: '/Game/Contract/TileSet', tileWidth: 32, tileHeight: 32, spacingX: 1, spacingY: 1, marginLeft: 2, marginTop: 2, marginRight: 2, marginBottom: 2, drawingOffsetX: 0, drawingOffsetY: 0, backgroundColor: { r: 0.1, g: 0.2, b: 0.3, a: 1 }, save: true }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'get_tile_set_tile_uv', assetPath: '/Game/Contract/TileSet', tileIndex: 0 }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'configure_tile_set_tile_metadata', assetPath: '/Game/Contract/TileSet', tileIndex: 0, tileUserData: 'Grass', save: true }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'inspect_tile_set_tile_metadata', assetPath: '/Game/Contract/TileSet', tileIndex: 0 }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'get_tile_set_tile_xy', assetPath: '/Game/Contract/TileSet', textureU: 32, textureV: 32, roundUp: false }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'get_tile_set_uv_from_xy', assetPath: '/Game/Contract/TileSet', tileX: 1, tileY: 1 }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'create_tile_map', name: 'ContractTileMap', path: '/Game/Contract', tileSetPath: '/Game/Contract/TileSet', save: true }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'inspect_tile_map', assetPath: '/Game/Contract/TileMap' }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'configure_tile_map_visuals', assetPath: '/Game/Contract/TileMap', backgroundColor: { r: 0.05, g: 0.05, b: 0.05, a: 1 }, tileGridColor: { r: 1, g: 1, b: 1, a: 0.25 }, multiTileGridWidth: 4, multiTileGridHeight: 4, save: true }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'configure_tile_map_layer', assetPath: '/Game/Contract/TileMap', layerIndex: 0, layerColor: { r: 1, g: 1, b: 1, a: 1 }, layerCollides: true, renderInEditor: true, save: true }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'inspect_tile_map_layer', assetPath: '/Game/Contract/TileMap', layerIndex: 0 }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'set_tile_map_cell', assetPath: '/Game/Contract/TileMap', layerIndex: 0, x: 0, y: 0, tileIndex: 0, flags: 3, tileSetPath: '/Game/Contract/TileSet', save: true }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'get_tile_map_cell', assetPath: '/Game/Contract/TileMap', layerIndex: 0, x: 0, y: 0 }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'fill_tile_map_region', assetPath: '/Game/Contract/TileMap', layerIndex: 0, x: 0, y: 0, width: 4, height: 3, tileIndex: 0, flags: 3, tileSetPath: '/Game/Contract/TileSet', rebuildCollision: true, save: true }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'get_tile_map_tile_geometry', assetPath: '/Game/Contract/TileMap', layerIndex: 0, tileX: 1, tileY: 1 }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'get_tile_map_tile_coordinates', assetPath: '/Game/Contract/TileMap', position: { x: 32, y: 32, z: 0 } }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'resize_tile_map', assetPath: '/Game/Contract/TileMap', width: 64, height: 32, forceResize: true, save: true }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'set_sprite_pivot', assetPath: '/Game/Contract/Sprite', pivotMode: 'center_center', rebuildData: true, save: true }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'inspect_sprite', assetPath: '/Game/Contract/Sprite' }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'configure_sprite_source', assetPath: '/Game/Contract/Sprite', trimmed: true, sourceOriginX: 0, sourceOriginY: 0, sourceWidth: 64, sourceHeight: 64, rebuildData: true, save: true }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'configure_sprite_collision', assetPath: '/Game/Contract/Sprite', collisionDomain: '3d', collisionThickness: 10, rebuildData: true, save: true }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'inspect_sprite_sockets', assetPath: '/Game/Contract/Sprite' }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'get_sprite_socket_transform', assetPath: '/Game/Contract/Sprite', socketName: 'Muzzle' }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'remove_sprite_socket', assetPath: '/Game/Contract/Sprite', socketName: 'Muzzle', save: true }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'validate_sprite_socket_names', assetPath: '/Game/Contract/Sprite', save: true }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'find_sprite_texture_bounding_box', assetPath: '/Game/Contract/Sprite', alphaThreshold: 0.1 }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'inspect_flipbook', assetPath: '/Game/Contract/ContractFlipbook' }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'get_flipbook_socket_transform', assetPath: '/Game/Contract/ContractFlipbook', socketName: 'Muzzle', keyFrameIndex: 0 }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'get_flipbook_sprite_at_time', assetPath: '/Game/Contract/ContractFlipbook', time: 0.5, clampToEnds: true }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'get_flipbook_sprite_at_frame', assetPath: '/Game/Contract/ContractFlipbook', frameIndex: 0 }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'configure_tile_map_collision', assetPath: '/Game/Contract/TileMap', collisionDomain: '3d', collisionThickness: 10, save: true }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'add_flipbook_keyframe', assetPath: '/Game/Contract/ContractFlipbook', spritePath: '/Game/Contract/SpriteA', frameRun: 2, keyFrameIndex: 0, save: true }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'set_flipbook_framerate', assetPath: '/Game/Contract/ContractFlipbook', framesPerSecond: 12, save: true }, expected: 'success|error' },
  { toolName: 'control_actor', arguments: { action: 'add_instance', actorName: 'ContractActor', componentName: 'ContractISM', location: { x: 0, y: 0, z: 0 }, rotation: { pitch: 0, yaw: 0, roll: 0 }, scale: { x: 1, y: 1, z: 1 }, worldSpace: true }, expected: 'success|error' },
  { toolName: 'control_actor', arguments: { action: 'update_instance_transform', actorName: 'ContractActor', componentName: 'ContractISM', instanceIndex: 0, location: { x: 100, y: 0, z: 0 }, rotation: { pitch: 0, yaw: 45, roll: 0 }, scale: { x: 1, y: 1, z: 1 } }, expected: 'success|error' },
  { toolName: 'control_actor', arguments: { action: 'remove_instance', actorName: 'ContractActor', componentName: 'ContractISM', instanceIndex: 0 }, expected: 'success|error' },
  { toolName: 'control_actor', arguments: { action: 'configure_instance_culling', actorName: 'ContractActor', componentName: 'ContractISM', startCullDistance: 1000, endCullDistance: 5000, minDrawDistance: 100 }, expected: 'success|error' },
  { toolName: 'control_actor', arguments: { action: 'configure_instance_lod', actorName: 'ContractActor', componentName: 'ContractHISM', lodDistanceScale: 0.75, useGpuLodSelection: true }, expected: 'success|error' },
  { toolName: 'manage_effect', arguments: { action: 'create_effect_pool', poolName: 'ContractEffects', systemPath: '/Game/MCPTest/ContractNiagara.ContractNiagara', poolSize: 4, ownershipPolicy: 'pool' }, expected: 'success|error' },
  { toolName: 'manage_effect', arguments: { action: 'spawn_pooled_effect', poolName: 'ContractEffects', actorName: 'ContractPooledEffect', location: { x: 0, y: 0, z: 100 } }, expected: 'success|error' },
  { toolName: 'manage_effect', arguments: { action: 'release_pooled_effect', poolName: 'ContractEffects', actorName: 'ContractPooledEffect' }, expected: 'success|error' },
  { toolName: 'control_editor', arguments: { action: 'configure_recorded_tracks', recordToPossessable: true, removeRedundantTracks: true, saveRecordedAssets: false }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'create_data_asset', path: '/Game/MCPTest', name: 'ContractDataAsset', classPath: '/Script/Engine.DataAsset', properties: {}, save: false }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'create_primary_data_asset', path: '/Game/MCPTest', name: 'ContractPrimaryDataAsset', classPath: '/Script/Engine.PrimaryAssetLabel', properties: {}, save: false }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'get_data_asset_properties', assetPath: '/Game/MCPTest/ContractDataAsset' }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'set_data_asset_properties', assetPath: '/Game/MCPTest/ContractDataAsset', properties: {}, save: false }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'create_data_table', path: '/Game/MCPTest', name: 'ContractDataTable', rowStructPath: '/Script/Engine.TableRowBase', save: false }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'compile_shaders', shaderMode: 'changed' }, expected: 'success|error|timeout' },
  { toolName: 'system_control', arguments: { action: 'create_device_profile', profileName: 'ContractWin64', profileType: 'Windows', cvars: { 'r.TextureQuality': 2 } }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'set_cvar_for_profile', profileName: 'ContractWin64', cvarName: 'r.TextureQuality', cvarValue: 3 }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'configure_build_settings', configName: 'DefaultEngine.ini', section: '/Script/Engine.Engine', key: 'bSmoothFrameRate', value: 'True' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'configure_platform_settings', configName: 'DefaultEngine.ini', section: '/Script/Engine.Engine', key: 'ConsoleClassName', value: 'GenericConsole' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'create_pak_file', platform: 'Win64', configuration: 'Development' }, expected: 'success|error|timeout' },
  { toolName: 'system_control', arguments: { action: 'configure_compression', platform: 'Win64', configuration: 'Development' }, expected: 'success|error|timeout' },
  { toolName: 'system_control', arguments: { action: 'configure_asset_encryption', platform: 'Win64', configuration: 'Development' }, expected: 'success|error|timeout' },
  { toolName: 'system_control', arguments: { action: 'create_test_level', levelName: 'ContractTestLevel' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'run_gauntlet_test', testName: 'UE.BootTest', platform: 'Win64', configuration: 'Development' }, expected: 'success|error|timeout' },
  { toolName: 'system_control', arguments: { action: 'configure_test_settings', configName: 'DefaultEngine.ini', section: '/Script/FunctionalTesting.FunctionalTestingSettings', key: 'bEnableFunctionalTesting', value: 'True' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'configure_demo_settings', configName: 'DefaultEngine.ini', section: '/Script/Engine.DemoNetDriver', key: 'demo.RecordHz', value: '8' }, expected: 'success|error' },
  { toolName: 'control_editor', arguments: { action: 'configure_take_sources', actorNames: ['ContractActor'], reduceKeys: false, showProgress: false }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'configure_localization_target', localizationTargetName: 'ContractGame', localizationConfig: '[CommonSettings]\nNativeCulture=en\nCulturesToGenerate=en\n' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'import_localization', localizationConfigPath: 'Config/Localization/ContractGame_Gather.ini' }, expected: 'success|error|timeout' },
  { toolName: 'system_control', arguments: { action: 'export_localization', localizationConfigPath: 'Config/Localization/ContractGame_Gather.ini' }, expected: 'success|error|timeout' },
  { toolName: 'system_control', arguments: { action: 'create_build_target', targetName: 'ContractGame', targetType: 'Game', filePath: 'Source/ContractGame.Target.cs' }, expected: 'success|error' },
  { toolName: 'manage_level_structure', arguments: { action: 'configure_hlod_transition', hlodLayerName: 'ContractHLOD', cellSize: 25600, loadingDistance: 50000 }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'create_tag_table', path: '/Game/MCPTest', name: 'ContractTagTable', save: false }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'add_data_table_row', assetPath: '/Game/MCPTest/ContractDataTable', rowName: 'ContractRow', properties: {}, save: false }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'modify_data_table_row', assetPath: '/Game/MCPTest/ContractDataTable', rowName: 'ContractRow', properties: {}, save: false }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'delete_data_table_row', assetPath: '/Game/MCPTest/ContractDataTable', rowName: 'ContractRow', save: false }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'import_data_table_csv', assetPath: '/Game/MCPTest/ContractDataTable', csv: 'Name,Value\nRow,1', save: false }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'export_data_table_csv', assetPath: '/Game/MCPTest/ContractDataTable' }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'get_data_table_rows', assetPath: '/Game/MCPTest/ContractDataTable' }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'create_curve_table', path: '/Game/MCPTest', name: 'ContractCurveTable', save: false }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'create_curve_float', path: '/Game/MCPTest', name: 'ContractCurveFloat', keys: [{ time: 0, value: 0 }, { time: 1, value: 1, interpMode: 'cubic', tangentMode: 'user', leaveTangent: 1 }], save: false }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'create_curve_linear_color', path: '/Game/MCPTest', name: 'ContractCurveColor', keys: [{ time: 0, value: { r: 0, g: 0, b: 0, a: 1 } }, { time: 1, value: { r: 1, g: 0.5, b: 0, a: 1 }, interpMode: 'linear' }], save: false }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'add_curve_table_row', assetPath: '/Game/MCPTest/ContractCurveTable', rowName: 'ContractCurve', keys: [{ time: 0, value: 0, interpMode: 'cubic', tangentMode: 'user', tangentWeightMode: 'both', arriveTangent: 0, leaveTangent: 1, arriveTangentWeight: 0.5, leaveTangentWeight: 0.5 }], save: false }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'get_curve_table_rows', assetPath: '/Game/MCPTest/ContractCurveTable' }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'import_curve_table_csv', assetPath: '/Game/MCPTest/ContractCurveTable', csv: 'Name,ContractCurve\n0,0', save: false }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'export_curve_table_csv', assetPath: '/Game/MCPTest/ContractCurveTable' }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'create_media_player', path: '/Game/MCPTest', name: 'ContractMediaPlayer', save: false }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'create_media_source', path: '/Game/MCPTest', name: 'ContractMediaSource', mediaUrl: 'https://example.invalid/contract.mp4', mediaType: 'stream', save: false }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'create_media_texture', path: '/Game/MCPTest', name: 'ContractMediaTexture', mediaPlayerPath: '/Game/MCPTest/ContractMediaPlayer', save: false }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'create_media_playlist', path: '/Game/MCPTest', name: 'ContractMediaPlaylist', mediaSourcePath: '/Game/MCPTest/ContractMediaSource', save: false }, expected: 'success|error' },
  { toolName: 'manage_audio', arguments: { action: 'validate_audio_asset', assetPath: '/Game/MCPTest/ContractSound', minDuration: 0.25, maxDuration: 30, requiredSampleRate: 48000, requiredChannels: 2, requireKnownType: true }, expected: 'success|error' },
  { toolName: 'manage_audio', arguments: { action: 'create_localization_manifest', projectPath: 'ContractProject', manifestPath: 'Content/Localization/Contract.json', targetName: 'ContractTarget', sourceCulture: 'en', cultures: ['en', 'fr'], entries: [] }, expected: 'success|error' },
  { toolName: 'manage_audio', arguments: { action: 'add_localization_entry', projectPath: 'ContractProject', manifestPath: 'Content/Localization/Contract.json', entry: { key: 'Contract.Greeting', sourceText: 'Hello', translations: { fr: 'Bonjour' }, voiceAssets: { fr: '/Game/Audio/ContractGreeting' } }, replaceExisting: true }, expected: 'success|error' },
  { toolName: 'manage_audio', arguments: { action: 'add_localization_entry', projectPath: 'ContractProject', manifestPath: 'Content/Localization/Contract.json', key: 'Contract.Bye', sourceText: 'Goodbye', translations: { fr: 'Au revoir' }, voiceAssets: { fr: '/Game/Audio/ContractBye' } }, expected: 'success|error' },
  { toolName: 'manage_audio', arguments: { action: 'validate_localization_manifest', projectPath: 'ContractProject', manifestPath: 'Content/Localization/Contract.json', requiredCultures: ['en', 'fr'], requireTranslations: true, requireVoiceAssets: true }, expected: 'success|error' },
  { toolName: 'manage_effect', arguments: { action: 'set_lifespan', actorName: 'ContractEffect', lifespanSeconds: 10 }, expected: 'success|error' },
  { toolName: 'manage_effect', arguments: { action: 'destroy_effect', actorName: 'ContractEffect' }, expected: 'success|error' },
  { toolName: 'control_editor', arguments: { action: 'open_media', mediaPlayerPath: '/Game/MCPTest/ContractMediaPlayer', mediaUrl: 'https://example.invalid/contract.mp4' }, expected: 'success|error' },
  { toolName: 'control_editor', arguments: { action: 'play_media', mediaPlayerPath: '/Game/MCPTest/ContractMediaPlayer' }, expected: 'success|error' },
  { toolName: 'control_editor', arguments: { action: 'pause_media', mediaPlayerPath: '/Game/MCPTest/ContractMediaPlayer' }, expected: 'success|error' },
  { toolName: 'control_editor', arguments: { action: 'seek_media', mediaPlayerPath: '/Game/MCPTest/ContractMediaPlayer', mediaTime: 1.5 }, expected: 'success|error' },
  { toolName: 'control_editor', arguments: { action: 'start_take_recording', sequencePath: '/Game/Contract/ContractSequence', openSequencer: false, showErrorMessage: false }, expected: 'success|error' },
  { toolName: 'control_editor', arguments: { action: 'stop_take_recording' }, expected: 'success|error' },
  { toolName: 'control_editor', arguments: { action: 'get_take_recording_status' }, expected: 'success|error' },
  { toolName: 'manage_sequence', arguments: { action: 'configure_shot_settings', path: '/Game/MCPTest/ContractSequence', shotIndex: 0, shotDisplayName: 'Contract Shot', thumbnailReferenceOffset: 0.5 }, expected: 'success|error' },
  { toolName: 'manage_sequence', arguments: { action: 'inspect_shot_settings', path: '/Game/MCPTest/ContractSequence', shotIndex: 0 }, expected: 'success|error' },
  { toolName: 'manage_sequence', arguments: { action: 'add_audio_track', path: '/Game/MCPTest/ContractSequence', soundPath: '/Game/MCPTest/ContractSound', frame: 0, durationFrames: 60, rowIndex: 0 }, expected: 'success|error' },
  { toolName: 'manage_sequence', arguments: { action: 'add_material_parameter_track', path: '/Game/MCPTest/ContractSequence', actorName: 'ContractActor', parameterName: 'Roughness', frame: 0, value: 0.5, rowIndex: 0 }, expected: 'success|error' },
  { toolName: 'manage_sequence', arguments: { action: 'add_material_color_track', path: '/Game/MCPTest/ContractSequence', actorName: 'ContractActor', parameterName: 'Tint', frame: 0, colorR: 1, colorG: 0.5, colorB: 0.25, colorA: 1, rowIndex: 0 }, expected: 'success|error' },
  { toolName: 'manage_sequence', arguments: { action: 'add_custom_primitive_data_track', path: '/Game/MCPTest/ContractSequence', actorName: 'ContractActor', customPrimitiveDataIndex: 0, frame: 0, value: 1, rowIndex: 0 }, expected: 'success|error' },
  { toolName: 'manage_sequence', arguments: { action: 'add_niagara_system_track', path: '/Game/MCPTest/ContractSequence', actorName: 'ContractActor', startFrame: 0, endFrame: 60 }, expected: 'success|error' },
  { toolName: 'manage_sequence', arguments: { action: 'create_niagara_float_parameter_track', path: '/Game/MCPTest/ContractSequence', actorName: 'ContractActor', parameterName: 'User.Rate' }, expected: 'success|error' },
  { toolName: 'manage_sequence', arguments: { action: 'add_niagara_float_parameter_key', path: '/Game/MCPTest/ContractSequence', actorName: 'ContractActor', parameterName: 'User.Rate', frame: 0, value: 1, rowIndex: 0 }, expected: 'success|error' },
  { toolName: 'manage_sequence', arguments: { action: 'inspect_niagara_parameter_track', path: '/Game/MCPTest/ContractSequence', actorName: 'ContractActor' }, expected: 'success|error' },
  { toolName: 'manage_sequence', arguments: { action: 'add_niagara_integer_parameter_key', path: '/Game/MCPTest/ContractSequence', actorName: 'ContractActor', parameterName: 'User.Count', frame: 0, value: 1, rowIndex: 0 }, expected: 'success|error' },
  { toolName: 'manage_sequence', arguments: { action: 'add_niagara_bool_parameter_key', path: '/Game/MCPTest/ContractSequence', actorName: 'ContractActor', parameterName: 'User.Enabled', frame: 0, value: true, rowIndex: 0 }, expected: 'success|error' },
  { toolName: 'manage_sequence', arguments: { action: 'add_niagara_vector_parameter_key', path: '/Game/MCPTest/ContractSequence', actorName: 'ContractActor', parameterName: 'User.Direction', frame: 0, vectorX: 1, vectorY: 0, vectorZ: 0, rowIndex: 0 }, expected: 'success|error' },
  { toolName: 'manage_sequence', arguments: { action: 'add_niagara_color_parameter_key', path: '/Game/MCPTest/ContractSequence', actorName: 'ContractActor', parameterName: 'User.Color', frame: 0, colorR: 1, colorG: 0.5, colorB: 0.25, colorA: 1, rowIndex: 0 }, expected: 'success|error' },
  { toolName: 'control_editor', arguments: { action: 'start_demo_recording', filename: 'ContractDemoAlias' }, expected: 'success|error' },
  { toolName: 'control_editor', arguments: { action: 'stop_demo_recording' }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'inspect_asset_capabilities', assetPath: '/Game/MCPTest/ContractDataAsset' }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'fixup_redirectors', directoryPath: '/Game/MCPTest', checkoutFiles: false }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'verify_asset_persistence', assetPath: '/Game/MCPTest/ContractDataAsset', requireClean: true }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'verify_asset_persistence', assetPath: '/Game/MCPTest/ContractDataAsset', requireClean: true, verifyReload: true }, expected: 'success|error' },
  { toolName: 'manage_blueprint', arguments: { action: 'add_node', blueprintPath: '/Game/MCPTest/ContractBlueprint', graphName: 'EventGraph', nodeClass: '/Script/BlueprintGraph.K2Node_ExecutionSequence', posX: 100, posY: 100 }, expected: 'success|error' },

  { toolName: 'build_environment', arguments: { action: 'conform_spline_to_landscape' }, expected: 'success|error' },
  { toolName: 'build_environment', arguments: { action: 'create_landscape_edit_layer', landscapeActor: 'ContractLandscape', editLayerName: 'ContractLayer' }, expected: 'success|error' },
  { toolName: 'build_environment', arguments: { action: 'inspect_world_building_capabilities' }, expected: 'success|error' },
  { toolName: 'build_environment', arguments: { action: 'list_landscape_edit_layers', landscapeActor: 'ContractLandscape' }, expected: 'success|error' },
  { toolName: 'build_environment', arguments: { action: 'remove_landscape_edit_layer', landscapeActor: 'ContractLandscape', editLayerName: 'ContractLayer' }, expected: 'success|error' },
  { toolName: 'build_environment', arguments: { action: 'verify_landscape_edit_layers', editLayerNames: ['ContractLayer'], reloadForVerification: false, verifyPersistence: false }, expected: 'success|error' },

  { toolName: 'system_control', arguments: { action: 'run_uat', uatOperation: 'build_server', projectPath: 'Contract.uproject', async: true, server: true, serverConfiguration: 'Development', compressed: true, encryptIniFiles: true, encryptPakIndex: true, includePrerequisites: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'cook_content', projectPath: 'Contract.uproject', platform: 'Win64', async: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'package_project', projectPath: 'Contract.uproject', platform: 'Win64', async: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'validate_release', archiveDirectory: 'ContractArchive', requiredFiles: ['Contract.uproject'], requirePak: false, manifestPath: 'release-manifest.json' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'validate_project', requiredFiles: ['Config/DefaultGame.ini'], requiredDirectories: ['Content', 'Config'], includeInventory: true, validationMode: 'data_validation', validationArguments: ['-AllowCommandletRendering'], enginePath: 'C:/UnrealEngine', timeoutMs: 120000 }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'run_data_validation', enginePath: 'C:/UnrealEngine', validationArguments: ['-AllowCommandletRendering'], timeoutMs: 120000 }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'create_asset_validator', className: 'UContractAssetValidator', headerPath: 'Source/Validation/ContractAssetValidator.h', sourcePath: 'Source/Validation/ContractAssetValidator.cpp', backup: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'create_game_architecture_manifest', projectPath: 'ContractProject', manifestPath: 'Config/Architecture/contract.json', projectName: 'ContractGame', requirements: [{ id: 'game-module', kind: 'module' }], backup: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'add_architecture_requirement', projectPath: 'ContractProject', manifestPath: 'Config/Architecture/contract.json', requirement: { id: 'main-map', kind: 'asset', path: 'Content/Maps/Main.umap', required: true }, replaceExisting: true, backup: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'add_architecture_requirement', projectPath: 'ContractProject', manifestPath: 'Config/Architecture/contract.json', requirementId: 'optional-doc', requirementKind: 'file', requirementPath: 'Config/Architecture/README.md', description: 'Architecture notes', required: false, replaceExisting: true, backup: false }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'validate_game_architecture', projectPath: 'ContractProject', manifestPath: 'Config/Architecture/contract.json', includeOptional: true }, expected: 'success|error' },
  { toolName: 'manage_effect', arguments: { action: 'create_effect_preset', projectPath: 'ContractProject', presetPath: 'Config/Effects/impact.json', presetName: 'Impact', actions: [{ action: 'create_impact_effect', args: { intensity: 1 } }], backup: true }, expected: 'success|error' },
  { toolName: 'manage_effect', arguments: { action: 'validate_effect_preset', projectPath: 'ContractProject', presetPath: 'Config/Effects/impact.json' }, expected: 'success|error' },
  { toolName: 'manage_effect', arguments: { action: 'apply_effect_preset', projectPath: 'ContractProject', presetPath: 'Config/Effects/impact.json' }, expected: 'success|error' },
  { toolName: 'manage_sequence', arguments: { action: 'render_sequence_queue', queue: [{ path: '/Game/Cinematics/Intro', outputPath: 'Saved/Renders/Intro' }], waitForCompletion: true, pollIntervalMs: 100, timeoutMs: 5000 }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'run_tests', projectPath: 'Contract.uproject', filter: 'Project.Contract', reportPath: 'contract-tests.json' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'get_test_results', projectPath: 'Contract.uproject', reportPath: 'contract-tests.json' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'start_session', channels: 'Frame,CPU,GPU' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'get_session_status' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'stop_session' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'check_map_errors' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'create_functional_test', testName: 'ContractFunctionalTest' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'create_functional_test', testName: 'ContractConfiguredFunctionalTest', enabled: false, timeLimit: 120, saveLevel: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'runtime_health' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'get_runtime_capabilities' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'get_runtime_world' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'get_runtime_actors', limit: 25, classFilter: 'Pawn' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'get_runtime_actor', actorName: 'PlayerPawn' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'enable_gameplay_debugger', category: 'AI', enabled: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'create_automation_test', projectPath: 'ContractProject', className: 'FContractAutomationTest', testName: 'Project.Contract.Automation', headerPath: 'Source/ContractAutomationTest.h', sourcePath: 'Source/ContractAutomationTest.cpp', dryRun: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'validate_blueprints', paths: ['/Game'], recursive: true, maxAssets: 25, saveAfterCompile: false }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'start_memory_report' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'configure_stat_commands', statNames: ['fps', 'unit'], enabled: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'check_for_errors', logCategories: ['MapCheck', 'BlueprintLog'] }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'capture_insights_trace', tracePath: 'contract.utrace', channels: 'Cpu,GPU' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'analyze_trace', archiveDirectory: 'ContractArchive', tracePath: 'contract.utrace', async: true, dryRun: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'start_network_profiler', enabled: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'enable_visual_logger', enabled: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'add_visual_log_entry', visualLogText: 'Contract marker', visualLogCategory: 'MCP' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'manage_project_plugin', pluginAction: 'list' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'list_plugins' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'get_plugin_status', pluginName: 'ContractPlugin' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'enable_plugin', pluginName: 'ContractPlugin', backup: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'disable_plugin', pluginName: 'ContractPlugin', backup: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'manage_project_plugin', pluginAction: 'validate' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'manage_project_plugin', pluginAction: 'enable', pluginName: 'ContractPlugin', backup: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'inspect_platform_capabilities', enginePath: 'C:/UnrealEngine' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'sign_release', platform: 'Win64', projectPath: 'C:/Contract', artifactPath: 'Build/Contract.exe', signingIdentity: 'CONTRACT_THUMBPRINT', dryRun: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'sign_release', platform: 'Win64', projectPath: 'C:/Contract', artifactPath: 'Build/Contract.exe', certificatePath: 'keys/contract.pfx', dryRun: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'sign_release', platform: 'Android', archiveDirectory: 'ContractArchive', artifactPath: 'Contract.apk', keystorePath: 'keys/contract.jks', signingAlias: 'contract', signingPasswordEnv: 'CONTRACT_SIGNING_PASSWORD', dryRun: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'run_packaged', archiveDirectory: 'ContractArchive', artifactPath: 'Contract.exe', arguments: '-log -nullrhi', async: true, dryRun: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'deploy_package', platform: 'Android', archiveDirectory: 'ContractArchive', artifactPath: 'Contract.apk', deviceId: 'emulator-5554', dryRun: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'deploy_package', platform: 'Win64', archiveDirectory: 'ContractArchive', artifactPath: 'ContractGame', destinationDirectory: 'LocalStaging', overwrite: true, dryRun: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'run_network_soak', archiveDirectory: 'ContractArchive', serverArtifactPath: 'Server.exe', clientArtifactPath: 'Client.exe', clientCount: 2, serverPort: 7777, durationMs: 5000, serverStartupTimeoutMs: 1000, clientStartupTimeoutMs: 1500, serverReadyPattern: 'LogNet: Ready', clientReadyPattern: 'LogNet: Join succeeded', async: true, serverArguments: '-log', clientArguments: '-log', dryRun: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'release_gate', archiveDirectory: 'ContractArchive', requiredFiles: ['Game.pak'], requiredDirectories: ['Binaries'], projectRequiredFiles: ['Nebula.uproject'], projectRequiredDirectories: ['Source'], architectureManifestPath: 'Config/Architecture/contract.json', validateArchitecture: true, requirePak: true, manifestPath: 'release-manifest.json', runProjectValidation: false, runAutomationTests: true, runPackagedSmoke: true, packagedArtifactPath: 'ContractGame.exe', testName: 'Project.Functional', filter: 'Project', reportPath: 'release-tests.json', validatePlugins: false }, expected: 'success|error' },
  { toolName: 'manage_pcg', arguments: { action: 'regenerate_pcg_component', actorName: 'ContractPCG', componentName: 'PCGComponent', wait: true, async: true, timeoutMs: 1000, save: false }, expected: 'success|error' },
  { toolName: 'manage_networking', arguments: { action: 'get_online_identity_status', localUserNum: 0 }, expected: 'success|error' },
  { toolName: 'manage_networking', arguments: { action: 'get_online_presence', localUserNum: 0 }, expected: 'success|error' },
  { toolName: 'manage_networking', arguments: { action: 'set_online_presence', localUserNum: 0, presenceState: 'online', statusText: 'In game' }, expected: 'success|error' },
  { toolName: 'manage_networking', arguments: { action: 'get_online_friends', localUserNum: 0, friendsListName: 'default', timeoutMs: 5000 }, expected: 'success|error' },
  { toolName: 'manage_networking', arguments: { action: 'send_online_friend_invite', localUserNum: 0, friendId: 'ContractFriendId', friendsListName: 'default', timeoutMs: 5000 }, expected: 'success|error' },
  { toolName: 'manage_networking', arguments: { action: 'accept_online_friend_invite', localUserNum: 0, friendId: 'ContractFriendId', friendsListName: 'default', timeoutMs: 5000 }, expected: 'success|error' },
  { toolName: 'manage_networking', arguments: { action: 'reject_online_friend_invite', localUserNum: 0, friendId: 'ContractFriendId', friendsListName: 'default' }, expected: 'success|error' },
  { toolName: 'manage_networking', arguments: { action: 'delete_online_friend', localUserNum: 0, friendId: 'ContractFriendId', friendsListName: 'default' }, expected: 'success|error' },
  { toolName: 'manage_level_structure', arguments: { action: 'build_hlods', async: true, timeoutSeconds: 10 }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'optimize_shaders', mode: 'changed', async: true, timeoutMs: 5000 }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'compile_material', assetPath: '/Game/ContractMaterial', async: true, timeoutMs: 5000, save: false }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'get_job_status', jobId: 'contract-job' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'wait_for_job', jobId: 'contract-job', timeoutMs: 1000 }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'wait_for_async_action', asyncId: 'contract-async', timeoutMs: 1000, pollIntervalMs: 50 }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'list_jobs' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'cancel_job', jobId: 'contract-job' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'read_project_file', filePath: 'Config/DefaultGame.ini' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'write_project_file', filePath: 'Config/Contract.ini', content: '[Contract]\nEnabled=True', backup: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'generate_save_game_class', className: 'UContractSaveGame', headerPath: 'Source/Contract/ContractSaveGame.h', sourcePath: 'Source/Contract/ContractSaveGame.cpp', variables: [{ name: 'Score', type: 'int32', defaultValue: 0 }], schemaVersion: 2, migrationManifestPath: 'Config/SaveGame/ContractSaveGame.schema.json', migrations: [{ fromVersion: 1, toVersion: 2, description: 'Add score field' }], backup: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'configure_checkpoint_data', className: 'UContractCheckpointSaveGame', headerPath: 'Source/Contract/ContractCheckpointSaveGame.h', sourcePath: 'Source/Contract/ContractCheckpointSaveGame.cpp', variables: [{ name: 'CheckpointId', type: 'FName', defaultValue: 'Start' }], schemaVersion: 1, backup: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'list_gameplay_tags' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'add_gameplay_tag', tag: 'Contract.Test', comment: 'contract', backup: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'create_gameplay_tag', tag: 'Contract.Created', comment: 'contract', backup: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'register_native_tag', tag: 'Contract.Native', comment: 'contract runtime tag' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'create_string_table', stringTableId: 'ContractTable', namespace: 'Contract' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'add_string_entry', stringTableId: 'ContractTable', stringKey: 'Greeting', sourceString: 'Hello', devNotes: 'contract' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'get_localized_string', stringTableId: 'ContractTable', stringKey: 'Greeting' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'set_culture', culture: 'en-US' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'set_language_and_locale', culture: 'en-US' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'set_locale', culture: 'en-US' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'set_quality_level', level: 2 }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'configure_scalability_group', group: 'Shadow', level: 2 }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'generate_project_files', projectPath: 'Contract.uproject', arguments: '-CurrentPlatform' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'remove_gameplay_tag', tag: 'Contract.Test', backup: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'get_runtime_gameplay_tag', tag: 'Contract.Test' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'create_tag_container', tags: ['Contract.Test'] }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'add_tag_to_container', tags: ['Contract.Test'], tag: 'Contract.Test.Child' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'check_tag_match', tags: ['Contract.Test.Child'], matchTags: ['Contract.Test'], matchMode: 'any' }, expected: 'success|error' },
  { toolName: 'control_actor', arguments: { action: 'get_gameplay_tags', actorName: 'ContractActor' }, expected: 'success|error' },
  { toolName: 'control_actor', arguments: { action: 'add_gameplay_tag', actorName: 'ContractActor', tag: 'Contract.Test' }, expected: 'success|error' },
  { toolName: 'control_actor', arguments: { action: 'remove_gameplay_tag', actorName: 'ContractActor', tag: 'Contract.Test' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'list_config_layers' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'get_config_value', configName: 'DefaultGame.ini', section: 'Contract', key: 'Enabled' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'read_config_value', configName: 'DefaultGame.ini', section: 'Contract', key: 'Enabled' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'set_config_value', configName: 'DefaultGame.ini', section: 'Contract', key: 'Enabled', value: 'True', backup: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'write_config_value', configName: 'DefaultGame.ini', section: 'Contract', key: 'Enabled', value: 'True', backup: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'get_section', configName: 'DefaultGame.ini', section: 'Contract' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'create_config_section', configName: 'DefaultGame.ini', section: 'Contract', backup: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'reload_config', configName: 'DefaultGame.ini' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'flush_config', configName: 'DefaultGame.ini' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'get_config_hierarchy' }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'replace_curve_keys', assetPath: '/Game/Contract/Curve', keys: [{ time: 0, value: 0 }, { time: 1, value: 1, interpMode: 'linear' }], save: true }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'list_primary_assets', primaryAssetType: 'Map', limit: 20, offset: 0 }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'get_primary_asset', primaryAssetId: 'Map:Contract', assetPath: '/Game/Contract/Contract' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'save_game_to_slot', saveGameObject: '/Game/Contract/SG.SG', slotName: 'ContractSlot', userIndex: 0, async: true, timeoutMs: 5000 }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'load_game_from_slot', slotName: 'ContractSlot', userIndex: 0, async: true, timeoutMs: 5000 }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'inspect_save_game_schema', saveGameObject: '/Game/Contract/SG.SG' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'delete_save_game_slot', slotName: 'ContractSlot', userIndex: 0 }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'check_save_game_slot', slotName: 'ContractSlot', userIndex: 0 }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'list_save_game_slots', userIndex: 0 }, expected: 'success|error' },

  { toolName: 'inspect', arguments: { action: 'production_capabilities' }, expected: 'success|error' },
  { toolName: 'manage_ai', arguments: { action: 'inspect_ai_capabilities' }, expected: 'success|error' },
  { toolName: 'manage_networking', arguments: { action: 'get_online_capabilities', localUserNum: 0 }, expected: 'success|error' },
  { toolName: 'manage_networking', arguments: { action: 'get_online_session_status', sessionName: 'ContractSession', localUserNum: 0 }, expected: 'success|error' },
  { toolName: 'manage_networking', arguments: { action: 'configure_network_conditions', packetLagMs: 100, packetLossPercent: 2, packetDupPercent: 1, packetOrder: 0 }, expected: 'success|error' },
  { toolName: 'manage_networking', arguments: { action: 'configure_network_conditions', reset: true }, expected: 'success|error' },
  { toolName: 'manage_networking', arguments: { action: 'create_online_session', sessionName: 'ContractSession', localUserNum: 0, maxPlayers: 2, bIsLANMatch: true }, expected: 'success|error' },
  { toolName: 'manage_networking', arguments: { action: 'find_online_sessions', localUserNum: 0, maxSearchResults: 10, bIsLANMatch: true }, expected: 'success|error' },
  { toolName: 'manage_networking', arguments: { action: 'join_online_session', sessionName: 'ContractSession', localUserNum: 0, searchId: 'online-search-1', resultIndex: 0 }, expected: 'success|error' },
  { toolName: 'manage_networking', arguments: { action: 'destroy_online_session', sessionName: 'ContractSession', localUserNum: 0 }, expected: 'success|error' },
  { toolName: 'manage_sequence', arguments: { action: 'render_sequence_mrq', path: '/Game/Contract/ContractSequence', outputPath: 'Saved/MCP/MRQ/Contract' }, expected: 'success|error' },
  { toolName: 'manage_sequence', arguments: { action: 'render_sequence_mrq', path: '/Game/Contract/ContractSequence', outputPath: 'Saved/MCP/MRQ/Contract', outputFormat: 'png', resolution: '1280x720', startFrame: 0, endFrame: 10 }, expected: 'success|error' },
  { toolName: 'manage_sequence', arguments: { action: 'render_sequence_mrq', path: '/Game/Contract/ContractSequence', outputPath: 'Saved/MCP/MRQ/Contract', spatialSampleCount: 4, temporalSampleCount: 8 }, expected: 'success|error' },
  { toolName: 'manage_sequence', arguments: { action: 'render_sequence_mrq', path: '/Game/Contract/ContractSequence', outputPath: 'Saved/MCP/MRQ/Contract', outputFormat: 'exr', renderPass: 'object_id' }, expected: 'success|error' },
  { toolName: 'manage_sequence', arguments: { action: 'render_sequence_mrq', path: '/Game/Contract/ContractSequence', outputPath: 'Saved/MCP/MRQ/Contract', mrqPresetPath: '/Game/Contract/MRQ/DefaultConfig' }, expected: 'success|error' },
  { toolName: 'manage_sequence', arguments: { action: 'configure_burn_ins', path: '/Game/Contract/ContractSequence', outputPath: 'Saved/MCP/MRQ/Contract', compositeBurnIn: true }, expected: 'success|error' },
  { toolName: 'manage_sequence', arguments: { action: 'create_master_sequence', name: 'ContractMaster', path: '/Game/Contract' }, expected: 'success|error' },
  { toolName: 'manage_sequence', arguments: { action: 'create_cine_camera_actor', path: '/Game/Contract/ContractMaster', spawnable: true }, expected: 'success|error' },
  { toolName: 'manage_sequence', arguments: { action: 'add_subsequence', path: '/Game/Contract/ContractMaster', subsequencePath: '/Game/Contract/ContractShot', startFrame: 0, durationFrames: 120, rowIndex: 0 }, expected: 'success|error' },
  { toolName: 'manage_sequence', arguments: { action: 'add_subsequence', path: '/Game/Contract/ContractMaster', childSequencePath: '/Game/Contract/ContractShotAlias', durationFrames: 60 }, expected: 'success|error' },
  { toolName: 'manage_sequence', arguments: { action: 'add_shot_track', path: '/Game/Contract/ContractMaster' }, expected: 'success|error' },
  { toolName: 'animation_physics', arguments: { action: 'validate_animation_asset', assetPath: '/Game/Contract/ContractAnim', minDuration: 0.25, maxDuration: 30, expectedSkeletonPath: '/Game/Contract/ContractSkeleton' }, expected: 'success|error' },
  { toolName: 'manage_sequence', arguments: { action: 'add_camera_cut_track', path: '/Game/Contract/ContractMaster' }, expected: 'success|error' },
  { toolName: 'manage_sequence', arguments: { action: 'add_fade_track', path: '/Game/Contract/ContractMaster' }, expected: 'success|error' },
  { toolName: 'manage_sequence', arguments: { action: 'add_level_visibility_track', path: '/Game/Contract/ContractMaster' }, expected: 'success|error' },
  { toolName: 'manage_sequence', arguments: { action: 'add_skeletal_animation_track', path: '/Game/Contract/ContractMaster', actorName: 'ContractCharacter' }, expected: 'success|error' },
  { toolName: 'manage_sequence', arguments: { action: 'add_transform_track', path: '/Game/Contract/ContractMaster', actorName: 'ContractCharacter' }, expected: 'success|error' },
  { toolName: 'manage_sequence', arguments: { action: 'add_event_track', path: '/Game/Contract/ContractMaster' }, expected: 'success|error' },
  { toolName: 'manage_sequence', arguments: { action: 'add_property_track', path: '/Game/Contract/ContractMaster', actorName: 'ContractCharacter', property: 'Visibility' }, expected: 'success|error' },
  { toolName: 'manage_sequence', arguments: { action: 'get_mrq_status' }, expected: 'success|error' },
  { toolName: 'manage_sequence', arguments: { action: 'cancel_mrq', mrqJobId: 'contract-mrq-job' }, expected: 'success|error' },
  { toolName: 'control_actor', arguments: { action: 'create_media_sound_component', actorName: 'ContractMediaActor', mediaPlayerPath: '/Game/Contract/MediaPlayer' }, expected: 'success|error' },
  { toolName: 'control_actor', arguments: { action: 'configure_camera_settings', actorName: 'ContractCineCamera', focalLength: 50, aperture: 2.8, focusDistance: 1000, filmbackSensorWidth: 36, filmbackSensorHeight: 24 }, expected: 'success|error' },
  { toolName: 'control_actor', arguments: { action: 'configure_camera_rig_rail', actorName: 'ContractCameraRigRail', currentPositionOnRail: 0.5, lockOrientationToRail: true }, expected: 'success|error' },
  { toolName: 'control_actor', arguments: { action: 'configure_camera_rig_crane', actorName: 'ContractCameraRigCrane', craneArmLength: 250, cranePitch: -10, craneYaw: 20, lockMountPitch: false, lockMountYaw: true }, expected: 'success|error' },
  { toolName: 'control_editor', arguments: { action: 'play_demo', filename: 'ContractDemo' }, expected: 'success|error' },
  { toolName: 'control_editor', arguments: { action: 'pause_demo' }, expected: 'success|error' },
  { toolName: 'control_editor', arguments: { action: 'seek_demo', demoTime: 1.5 }, expected: 'success|error' },
  { toolName: 'control_editor', arguments: { action: 'set_demo_playback_speed', demoSpeed: 1.0 }, expected: 'success|error' },
  { toolName: 'control_editor', arguments: { action: 'configure_killcam_duration', durationSeconds: 5 }, expected: 'success|error' },
  { toolName: 'control_editor', arguments: { action: 'start_killcam', filename: 'ContractDemo', startTime: 10, durationSeconds: 5 }, expected: 'success|error' },
  { toolName: 'manage_level_structure', arguments: { action: 'get_wp_cell_status' }, expected: 'success|error' },
  { toolName: 'manage_level_structure', arguments: { action: 'load_cells' }, expected: 'success|error' },
  { toolName: 'manage_level_structure', arguments: { action: 'pin_wp_cells' }, expected: 'success|error' },
  { toolName: 'manage_level_structure', arguments: { action: 'prepare_pie_capture' }, expected: 'success|error' },
  { toolName: 'manage_level_structure', arguments: { action: 'unload_cells' }, expected: 'success|error' },
  { toolName: 'manage_level_structure', arguments: { action: 'unpin_wp_cells' }, expected: 'success|error' },
  { toolName: 'control_editor', arguments: { action: 'screenshot', screenshotPath: 'Contract.png' }, expected: 'success|error' },
  { toolName: 'manage_level_structure', arguments: { action: 'get_level_structure_info', reloadForVerification: false, verifyPersistence: false }, expected: 'success|error' }
]);
