import { runToolTests } from '../../test-runner.mjs';

// Static contract coverage for capabilities that are intentionally environment
// dependent. These cases ensure every advertised action and new parameter is
// represented in the validation matrix even when Unreal is not running.
await runToolTests('production-contract-coverage', [
  { toolName: 'manage_asset', arguments: { action: 'create_data_asset', path: '/Game/MCPTest', name: 'ContractDataAsset', classPath: '/Script/Engine.DataAsset', properties: {}, save: false }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'get_data_asset_properties', assetPath: '/Game/MCPTest/ContractDataAsset' }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'set_data_asset_properties', assetPath: '/Game/MCPTest/ContractDataAsset', properties: {}, save: false }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'create_data_table', path: '/Game/MCPTest', name: 'ContractDataTable', rowStructPath: '/Script/Engine.TableRowBase', save: false }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'add_data_table_row', assetPath: '/Game/MCPTest/ContractDataTable', rowName: 'ContractRow', properties: {}, save: false }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'get_data_table_rows', assetPath: '/Game/MCPTest/ContractDataTable' }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'create_curve_table', path: '/Game/MCPTest', name: 'ContractCurveTable', save: false }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'add_curve_table_row', assetPath: '/Game/MCPTest/ContractCurveTable', rowName: 'ContractCurve', keys: [{ time: 0, value: 0 }], save: false }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'get_curve_table_rows', assetPath: '/Game/MCPTest/ContractCurveTable' }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'import_curve_table_csv', assetPath: '/Game/MCPTest/ContractCurveTable', csv: 'Name,ContractCurve\n0,0', save: false }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'export_curve_table_csv', assetPath: '/Game/MCPTest/ContractCurveTable' }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'create_media_player', path: '/Game/MCPTest', name: 'ContractMediaPlayer', save: false }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'create_media_source', path: '/Game/MCPTest', name: 'ContractMediaSource', mediaUrl: 'https://example.invalid/contract.mp4', mediaType: 'stream', save: false }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'create_media_texture', path: '/Game/MCPTest', name: 'ContractMediaTexture', mediaPlayerPath: '/Game/MCPTest/ContractMediaPlayer', save: false }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'create_media_playlist', path: '/Game/MCPTest', name: 'ContractMediaPlaylist', mediaSourcePath: '/Game/MCPTest/ContractMediaSource', save: false }, expected: 'success|error' },
  { toolName: 'control_editor', arguments: { action: 'open_media', mediaPlayerPath: '/Game/MCPTest/ContractMediaPlayer', mediaUrl: 'https://example.invalid/contract.mp4' }, expected: 'success|error' },
  { toolName: 'control_editor', arguments: { action: 'play_media', mediaPlayerPath: '/Game/MCPTest/ContractMediaPlayer' }, expected: 'success|error' },
  { toolName: 'control_editor', arguments: { action: 'pause_media', mediaPlayerPath: '/Game/MCPTest/ContractMediaPlayer' }, expected: 'success|error' },
  { toolName: 'control_editor', arguments: { action: 'seek_media', mediaPlayerPath: '/Game/MCPTest/ContractMediaPlayer', mediaTime: 1.5 }, expected: 'success|error' },
  { toolName: 'control_editor', arguments: { action: 'start_take_recording', sequencePath: '/Game/Contract/ContractSequence', openSequencer: false, showErrorMessage: false }, expected: 'success|error' },
  { toolName: 'control_editor', arguments: { action: 'stop_take_recording' }, expected: 'success|error' },
  { toolName: 'control_editor', arguments: { action: 'get_take_recording_status' }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'inspect_asset_capabilities', assetPath: '/Game/MCPTest/ContractDataAsset' }, expected: 'success|error' },

  { toolName: 'build_environment', arguments: { action: 'conform_spline_to_landscape' }, expected: 'success|error' },
  { toolName: 'build_environment', arguments: { action: 'create_landscape_edit_layer', landscapeActor: 'ContractLandscape', editLayerName: 'ContractLayer' }, expected: 'success|error' },
  { toolName: 'build_environment', arguments: { action: 'inspect_world_building_capabilities' }, expected: 'success|error' },
  { toolName: 'build_environment', arguments: { action: 'list_landscape_edit_layers', landscapeActor: 'ContractLandscape' }, expected: 'success|error' },
  { toolName: 'build_environment', arguments: { action: 'remove_landscape_edit_layer', landscapeActor: 'ContractLandscape', editLayerName: 'ContractLayer' }, expected: 'success|error' },
  { toolName: 'build_environment', arguments: { action: 'verify_landscape_edit_layers', editLayerNames: ['ContractLayer'], reloadForVerification: false, verifyPersistence: false }, expected: 'success|error' },

  { toolName: 'system_control', arguments: { action: 'run_uat', uatOperation: 'build_server', projectPath: 'Contract.uproject', async: true, server: true, serverConfiguration: 'Development', compressed: true, encryptIniFiles: true, encryptPakIndex: true, includePrerequisites: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'validate_release', archiveDirectory: 'ContractArchive', requiredFiles: ['Contract.uproject'], requirePak: false, manifestPath: 'release-manifest.json' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'validate_project', requiredFiles: ['Config/DefaultGame.ini'], requiredDirectories: ['Content', 'Config'], includeInventory: true, validationMode: 'data_validation', validationArguments: ['-AllowCommandletRendering'], enginePath: 'C:/UnrealEngine', timeoutMs: 120000 }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'run_tests', projectPath: 'Contract.uproject', filter: 'Project.Contract', reportPath: 'contract-tests.json' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'start_session', channels: 'Frame,CPU,GPU' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'get_session_status' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'stop_session' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'check_map_errors' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'create_functional_test', testName: 'ContractFunctionalTest' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'validate_blueprints', paths: ['/Game'], recursive: true, maxAssets: 25, saveAfterCompile: false }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'start_memory_report' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'configure_stat_commands', statNames: ['fps', 'unit'], enabled: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'check_for_errors', logCategories: ['MapCheck', 'BlueprintLog'] }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'capture_insights_trace', tracePath: 'contract.utrace', channels: 'Cpu,GPU' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'manage_project_plugin', pluginAction: 'list' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'manage_project_plugin', pluginAction: 'validate' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'manage_project_plugin', pluginAction: 'enable', pluginName: 'ContractPlugin', backup: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'inspect_platform_capabilities', enginePath: 'C:/UnrealEngine' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'sign_release', platform: 'Win64', projectPath: 'C:/Contract', artifactPath: 'Build/Contract.exe', signingIdentity: 'CONTRACT_THUMBPRINT', dryRun: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'sign_release', platform: 'Win64', projectPath: 'C:/Contract', artifactPath: 'Build/Contract.exe', certificatePath: 'keys/contract.pfx', dryRun: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'sign_release', platform: 'Android', archiveDirectory: 'ContractArchive', artifactPath: 'Contract.apk', keystorePath: 'keys/contract.jks', signingAlias: 'contract', signingPasswordEnv: 'CONTRACT_SIGNING_PASSWORD', dryRun: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'run_packaged', archiveDirectory: 'ContractArchive', artifactPath: 'Contract.exe', arguments: '-log -nullrhi', async: true, dryRun: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'deploy_package', platform: 'Android', archiveDirectory: 'ContractArchive', artifactPath: 'Contract.apk', deviceId: 'emulator-5554', dryRun: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'run_network_soak', archiveDirectory: 'ContractArchive', serverArtifactPath: 'Server.exe', clientArtifactPath: 'Client.exe', clientCount: 2, serverPort: 7777, durationMs: 5000, async: true, serverArguments: '-log', clientArguments: '-log' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'get_job_status', jobId: 'contract-job' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'list_jobs' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'cancel_job', jobId: 'contract-job' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'read_project_file', filePath: 'Config/DefaultGame.ini' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'write_project_file', filePath: 'Config/Contract.ini', content: '[Contract]\nEnabled=True', backup: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'generate_save_game_class', className: 'UContractSaveGame', headerPath: 'Source/Contract/ContractSaveGame.h', sourcePath: 'Source/Contract/ContractSaveGame.cpp', variables: [{ name: 'Score', type: 'int32', defaultValue: 0 }], backup: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'list_gameplay_tags' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'add_gameplay_tag', tag: 'Contract.Test', comment: 'contract', backup: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'remove_gameplay_tag', tag: 'Contract.Test', backup: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'get_runtime_gameplay_tag', tag: 'Contract.Test' }, expected: 'success|error' },
  { toolName: 'control_actor', arguments: { action: 'get_gameplay_tags', actorName: 'ContractActor' }, expected: 'success|error' },
  { toolName: 'control_actor', arguments: { action: 'add_gameplay_tag', actorName: 'ContractActor', tag: 'Contract.Test' }, expected: 'success|error' },
  { toolName: 'control_actor', arguments: { action: 'remove_gameplay_tag', actorName: 'ContractActor', tag: 'Contract.Test' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'list_config_layers' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'get_config_value', configName: 'DefaultGame.ini', section: 'Contract', key: 'Enabled' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'set_config_value', configName: 'DefaultGame.ini', section: 'Contract', key: 'Enabled', value: 'True', backup: true }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'list_primary_assets', primaryAssetType: 'Map', limit: 20, offset: 0 }, expected: 'success|error' },
  { toolName: 'manage_asset', arguments: { action: 'get_primary_asset', primaryAssetId: 'Map:Contract', assetPath: '/Game/Contract/Contract' }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'save_game_to_slot', saveGameObject: '/Game/Contract/SG.SG', slotName: 'ContractSlot', userIndex: 0, async: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'load_game_from_slot', slotName: 'ContractSlot', userIndex: 0, async: true }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'delete_save_game_slot', slotName: 'ContractSlot', userIndex: 0 }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'check_save_game_slot', slotName: 'ContractSlot', userIndex: 0 }, expected: 'success|error' },
  { toolName: 'system_control', arguments: { action: 'list_save_game_slots', userIndex: 0 }, expected: 'success|error' },

  { toolName: 'inspect', arguments: { action: 'production_capabilities' }, expected: 'success|error' },
  { toolName: 'manage_ai', arguments: { action: 'inspect_ai_capabilities' }, expected: 'success|error' },
  { toolName: 'manage_networking', arguments: { action: 'get_online_capabilities', localUserNum: 0 }, expected: 'success|error' },
  { toolName: 'manage_networking', arguments: { action: 'get_online_session_status', sessionName: 'ContractSession', localUserNum: 0 }, expected: 'success|error' },
  { toolName: 'manage_networking', arguments: { action: 'configure_network_conditions', packetLagMs: 100, packetLossPercent: 2, packetDupPercent: 1, packetOrder: 0 }, expected: 'success|error' },
  { toolName: 'manage_networking', arguments: { action: 'configure_network_conditions', reset: true }, expected: 'success|error' },
  { toolName: 'manage_networking', arguments: { action: 'create_online_session', sessionName: 'ContractSession', localUserNum: 0, maxPlayers: 2, bIsLANMatch: true }, expected: 'success|error' },
  { toolName: 'manage_networking', arguments: { action: 'find_online_sessions', localUserNum: 0, maxSearchResults: 10, bIsLANMatch: true }, expected: 'success|error' },
  { toolName: 'manage_networking', arguments: { action: 'join_online_session', sessionName: 'ContractSession', localUserNum: 0, searchId: 'online-search-1', resultIndex: 0 }, expected: 'success|error' },
  { toolName: 'manage_networking', arguments: { action: 'destroy_online_session', sessionName: 'ContractSession', localUserNum: 0 }, expected: 'success|error' },
  { toolName: 'manage_sequence', arguments: { action: 'render_sequence_mrq', path: '/Game/Contract/ContractSequence', outputPath: 'Saved/MCP/MRQ/Contract' }, expected: 'success|error' },
  { toolName: 'manage_sequence', arguments: { action: 'get_mrq_status' }, expected: 'success|error' },
  { toolName: 'manage_sequence', arguments: { action: 'cancel_mrq', mrqJobId: 'contract-mrq-job' }, expected: 'success|error' },
  { toolName: 'control_editor', arguments: { action: 'play_demo', filename: 'ContractDemo' }, expected: 'success|error' },
  { toolName: 'control_editor', arguments: { action: 'pause_demo' }, expected: 'success|error' },
  { toolName: 'control_editor', arguments: { action: 'seek_demo', demoTime: 1.5 }, expected: 'success|error' },
  { toolName: 'control_editor', arguments: { action: 'set_demo_playback_speed', demoSpeed: 1.0 }, expected: 'success|error' },
  { toolName: 'manage_level_structure', arguments: { action: 'get_wp_cell_status' }, expected: 'success|error' },
  { toolName: 'manage_level_structure', arguments: { action: 'load_cells' }, expected: 'success|error' },
  { toolName: 'manage_level_structure', arguments: { action: 'pin_wp_cells' }, expected: 'success|error' },
  { toolName: 'manage_level_structure', arguments: { action: 'prepare_pie_capture' }, expected: 'success|error' },
  { toolName: 'manage_level_structure', arguments: { action: 'unload_cells' }, expected: 'success|error' },
  { toolName: 'manage_level_structure', arguments: { action: 'unpin_wp_cells' }, expected: 'success|error' },
  { toolName: 'control_editor', arguments: { action: 'screenshot', screenshotPath: 'Contract.png' }, expected: 'success|error' },
  { toolName: 'manage_level_structure', arguments: { action: 'get_level_structure_info', reloadForVerification: false, verifyPersistence: false }, expected: 'success|error' }
]);
