/**
 * Core Tool Schemas - Essential MCP tools for asset, actor, editor, level, system, and introspection control
 *
 * Tools included:
 * - manage_tools: Dynamic MCP tool management
 * - manage_asset: Asset creation, import, manipulation
 * - control_actor: Actor spawn, transform, physics, components
 * - control_editor: PIE, camera, console commands, screenshots
 * - manage_level: Level load/save, streaming, lighting
 * - system_control: Profiling, CVars, UBT, tests
 * - inspect: Object introspection
 */

import { addActionParamsSchema, commonSchemas } from '../tool-definition-utils.js';

const screenshotModeSchema = {
  type: 'string',
  enum: ['editor_viewport', 'game_viewport', 'full_editor_window'],
  description: 'Screenshot source. editor_viewport captures the active editor viewport; game_viewport captures the PIE/game viewport; full_editor_window captures the full Slate editor window and returns imageBase64 by default.'
};

/** MCP Tool Definition type for explicit annotation to avoid TS7056 */
export interface ToolDefinition {
  category?: 'core' | 'world' | 'gameplay' | 'utility';
  name: string;
  description: string;
  inputSchema: Record<string, unknown>;
  outputSchema?: Record<string, unknown>;
  [key: string]: unknown;
}

export const coreToolDefinitions: ToolDefinition[] = [
  {
    name: 'manage_tools',
    description: 'Dynamic MCP tool management. List canonical tools, view category counts, and enable/disable tools or categories at runtime.',
    category: 'core',
    inputSchema: {
      type: 'object',
      properties: {
        action: {
          type: 'string',
          enum: ['list_tools', 'list_categories', 'enable_tools', 'disable_tools', 'enable_category', 'disable_category', 'get_status', 'reset'],
          description: 'list_tools: show canonical tools with status. list_categories: show category counts. enable/disable_tools: toggle specific tools. enable/disable_category: toggle category. get_status: current state. reset: restore defaults.'
        },
        tools: { type: 'array', items: commonSchemas.stringProp, description: 'Tool names to enable/disable' },
        category: { type: 'string', description: 'Category name to enable/disable (core, world, gameplay, utility, all)' }
      },
      required: ['action']
    },
    outputSchema: {
      type: 'object',
      properties: {
        ...commonSchemas.outputBase,
        tools: { type: 'array', items: { type: 'object', properties: { name: { type: 'string' }, enabled: { type: 'boolean' }, category: { type: 'string' } } } },
        categories: { type: 'array', items: { type: 'object', properties: { name: { type: 'string' }, enabled: { type: 'boolean' }, toolCount: { type: 'number' } } } },
        enabledCount: { type: 'number' },
        disabledCount: { type: 'number' }
      }
    }
  },
  {
    name: 'manage_asset',
    category: 'core',
    description: 'Create/import/manage assets, material graphs, material instances, procedural textures, render targets, and dependency analysis.',
    inputSchema: {
      type: 'object',
      properties: {
        action: {
          type: 'string',
          enum: [
            'list', 'import', 'duplicate', 'duplicate_asset', 'rename', 'rename_asset', 'move', 'move_asset', 'delete', 'delete_asset', 'delete_assets', 'create_folder', 'search_assets',
            'get_dependencies', 'get_source_control_state', 'analyze_graph', 'get_asset_graph', 'create_thumbnail', 'set_tags', 'get_metadata', 'set_metadata', 'validate', 'fixup_redirectors', 'find_by_tag', 'generate_report', 'size_map_analysis',
            'set_view_settings', 'navigate_to_path', 'sync_to_asset', 'sync_to_folder',
            'create_collection', 'add_to_collection', 'set_asset_color', 'show_in_explorer',
            'set_search_text',
            'create_objective', 'set_objective_state', 'configure_objective_markers', 'configure_objective_progression', 'create_quest_data_asset', 'start_quest', 'complete_quest_objective', 'track_quest', 'create_dialogue_tree', 'add_dialogue_node', 'add_dialogue_choice', 'configure_dialogue_conditions',
            'create_primary_data_asset',
            'create_material', 'create_material_instance', 'create_render_target', 'create_data_asset', 'get_data_asset_properties', 'set_data_asset_properties', 'list_primary_assets', 'get_primary_asset', 'create_data_table', 'add_data_table_row', 'modify_data_table_row', 'delete_data_table_row', 'get_data_table_rows', 'create_curve_table', 'create_curve_float', 'create_curve_linear_color', 'replace_curve_keys', 'add_curve_table_row', 'get_curve_table_rows', 'import_curve_table_csv', 'export_curve_table_csv', 'create_media_player', 'create_media_source', 'create_media_texture', 'create_media_playlist', 'generate_lods', 'add_material_parameter', 'list_instances', 'reset_instance_parameters', 'exists', 'get_material_stats',
            'import_data_table_csv', 'export_data_table_csv',
            'nanite_rebuild_mesh', 'bulk_rename', 'bulk_delete', 'source_control_checkout', 'source_control_submit',
            'add_material_node', 'connect_material_pins', 'remove_material_node', 'break_material_connections', 'get_material_node_details', 'rebuild_material',
            'create_physical_material', 'set_friction', 'set_restitution', 'set_density',
            'configure_surface_type', 'assign_physical_material',
            'configure_physical_material', 'get_physical_material', 'clear_physical_material_override'
          ],
          description: 'Action to perform'
        },
        assetPath: commonSchemas.assetPath,
        directory: commonSchemas.directoryPath,
        classNames: commonSchemas.arrayOfStrings,
        packagePaths: commonSchemas.arrayOfStrings,
        recursivePaths: commonSchemas.booleanProp,
        recursiveClasses: commonSchemas.booleanProp,
        limit: commonSchemas.numberProp,
        sourcePath: commonSchemas.sourcePath,
        destinationPath: commonSchemas.destinationPath,
        assetPaths: commonSchemas.arrayOfStrings,
        lodCount: commonSchemas.numberProp,
        reductionSettings: commonSchemas.objectProp,
        nodeName: commonSchemas.name,
        eventName: commonSchemas.eventName,
        memberClass: commonSchemas.stringProp,
        posX: commonSchemas.numberProp,
        posY: commonSchemas.numberProp,
        newName: commonSchemas.newName,
        overwrite: commonSchemas.overwrite,
        save: commonSchemas.save,
        fixupRedirectors: commonSchemas.booleanProp,
        directoryPath: commonSchemas.directoryPath,
        name: commonSchemas.name,
        path: commonSchemas.directoryPath,
        parentMaterial: commonSchemas.materialPath,
        classPath: commonSchemas.assetPath,
        properties: commonSchemas.objectProp,
        keys: { type: 'array', items: { type: 'object', additionalProperties: true }, description: 'CurveTable keys with finite time/value plus optional interpMode, tangentMode, tangentWeightMode, and tangent values.' },
        csv: { type: 'string', maxLength: 1048576, description: 'CSV payload for CurveTable import/export.' },
        rowStructPath: commonSchemas.assetPath,
        rowName: commonSchemas.name,
        parameters: commonSchemas.objectProp,
        width: commonSchemas.numberProp,
        height: commonSchemas.numberProp,
        format: commonSchemas.stringProp,
        mediaUrl: commonSchemas.stringProp,
        mediaType: { type: 'string', enum: ['file', 'stream'] },
        mediaPlayerPath: commonSchemas.assetPath,
        mediaSourcePath: commonSchemas.assetPath,
        primaryAssetType: commonSchemas.stringProp,
        primaryAssetId: commonSchemas.stringProp,
        meshPath: commonSchemas.meshPath,
        enableNanite: commonSchemas.booleanProp,
        preserveArea: commonSchemas.booleanProp,
        trianglePercent: commonSchemas.numberProp,
        fallbackPercent: commonSchemas.numberProp,
        tag: commonSchemas.tagName,
        metadata: commonSchemas.objectProp,
        viewType: commonSchemas.stringProp,
        thumbnailSize: commonSchemas.stringProp,
        instanceName: commonSchemas.stringProp,
        saveConfig: commonSchemas.booleanProp,
        showEngineContent: commonSchemas.booleanProp,
        showPluginContent: commonSchemas.booleanProp,
        showDeveloperContent: commonSchemas.booleanProp,
        showFolders: commonSchemas.booleanProp,
        showEmptyFolders: commonSchemas.booleanProp,
        showCppFolders: commonSchemas.booleanProp,
        showLocalizedContent: commonSchemas.booleanProp,
        showFavorites: commonSchemas.booleanProp,
        searchAssetPaths: commonSchemas.booleanProp,
        searchClasses: commonSchemas.booleanProp,
        searchCollections: commonSchemas.booleanProp,
        filterRecursively: commonSchemas.booleanProp,
        sourcesExpanded: commonSchemas.booleanProp,
        contentBrowserPath: commonSchemas.directoryPath,
        collectionName: commonSchemas.stringProp,
        collectionShareType: commonSchemas.stringProp,
        collectionStorageMode: commonSchemas.stringProp,
        color: commonSchemas.objectProp,
        r: commonSchemas.numberProp,
        g: commonSchemas.numberProp,
        b: commonSchemas.numberProp,
        a: commonSchemas.numberProp,
        focusContentBrowser: commonSchemas.booleanProp,
        allowLockedBrowser: commonSchemas.booleanProp,
        newBrowser: commonSchemas.booleanProp,
        graphName: commonSchemas.graphName,
        nodeType: commonSchemas.stringProp,
        nodeId: commonSchemas.nodeId,
        sourceNodeId: commonSchemas.sourceNodeId,
        targetNodeId: commonSchemas.targetNodeId,
        inputName: commonSchemas.pinName,
        fromNodeId: commonSchemas.sourceNodeId,
        fromPin: commonSchemas.sourcePin,
        toNodeId: commonSchemas.targetNodeId,
        toPin: commonSchemas.targetPin,
        parameterName: commonSchemas.parameterName,
        value: commonSchemas.value,
        x: commonSchemas.numberProp,
        y: commonSchemas.numberProp,
        comment: commonSchemas.stringProp,
        parentNodeId: commonSchemas.nodeId,
        childNodeId: commonSchemas.nodeId,
        maxDepth: commonSchemas.numberProp,
        // Bulk operations (C++ TryGetStringField)
        prefix: commonSchemas.stringProp,
        suffix: commonSchemas.stringProp,
        searchText: commonSchemas.stringProp,
        replaceText: commonSchemas.stringProp,
        paths: commonSchemas.arrayOfStrings,
        // Source control (C++ TryGetStringField)
        description: commonSchemas.stringProp,
        checkoutFiles: commonSchemas.booleanProp,
        // Bulk delete
        showConfirmation: commonSchemas.booleanProp,
        // Material graph operations
        pinName: commonSchemas.pinName,
        desc: commonSchemas.stringProp,
        materialPath: commonSchemas.materialPath,
        texturePath: commonSchemas.texturePath,
        physicalMaterialPath: commonSchemas.assetPath,
        actorName: commonSchemas.actorName,
        componentName: commonSchemas.componentName,
        friction: commonSchemas.numberProp,
        staticFriction: commonSchemas.numberProp,
        restitution: commonSchemas.numberProp,
        density: commonSchemas.numberProp,
        surfaceType: commonSchemas.stringProp,
        surfaceName: commonSchemas.stringProp,
        frictionCombineMode: commonSchemas.stringProp,
        restitutionCombineMode: commonSchemas.stringProp,
        overrideFrictionCombineMode: commonSchemas.booleanProp,
        overrideRestitutionCombineMode: commonSchemas.booleanProp,
        expressionClass: commonSchemas.stringProp,
        coordinateIndex: commonSchemas.numberProp,
        parameterType: commonSchemas.stringProp,
        nodes: commonSchemas.arrayOfObjects,
        tags: commonSchemas.arrayOfStrings,
        // Handler aliases (alternative parameter names accepted by handler)
        folderPath: commonSchemas.directoryPath,
        sourceNode: commonSchemas.sourceNodeId,
        targetNode: commonSchemas.targetNodeId,
        outputPin: commonSchemas.sourcePin,
        inputPin: commonSchemas.targetPin,
        type: commonSchemas.stringProp,
        defaultValue: commonSchemas.value,
        expressionIndex: commonSchemas.nodeId
      },
      required: ['action']
    },
    outputSchema: {
      type: 'object',
      properties: {
        ...commonSchemas.outputBase,
        assets: commonSchemas.arrayOfObjects,
        paths: commonSchemas.arrayOfStrings,
        path: commonSchemas.stringProp,
        nodeId: commonSchemas.nodeId,
        details: commonSchemas.objectProp
      }
    }
  },
  {
    name: 'control_actor',
    category: 'core',
    description: 'Spawn and control actors, manage components/tags, collision profiles/channels, attach actors, and automate editor selection and grouping.',
    inputSchema: {
      type: 'object',
      properties: {
        action: {
          type: 'string',
          enum: [
            'spawn', 'spawn_actor', 'create_checkpoint_actor', 'create_world_marker', 'create_ping_system', 'create_targeting_component', 'spawn_blueprint',
            'configure_marker_widget', 'configure_marker_3d_2d', 'configure_marker_distance', 'configure_marker_occlusion', 'configure_photo_mode_camera', 'configure_photo_mode_poses', 'create_quest_manager', 'configure_lock_on_target', 'set_target_priority', 'configure_target_switching', 'configure_soft_lock', 'configure_aim_assist',
            'delete', 'destroy_actor', 'delete_by_tag', 'duplicate',
            'apply_force',
            'set_transform', 'teleport_actor', 'set_actor_location', 'set_actor_rotation', 'set_actor_scale', 'set_actor_transform',
            'get_transform', 'get_actor_transform',
            'set_visibility', 'set_actor_visible',
            'add_component', 'create_media_sound_component', 'configure_camera_settings', 'remove_component',
            'set_component_properties', 'set_component_property', 'get_component_property',
            'get_components', 'get_actor_components',
            'get_actor_bounds',
            'add_tag', 'remove_tag', 'get_gameplay_tags', 'add_gameplay_tag', 'remove_gameplay_tag',
            'find_by_tag', 'find_actors_by_tag',
            'find_by_name', 'find_actors_by_name',
            'find_by_class', 'find_actors_by_class',
            'select_actor', 'select_actors_by_class', 'select_actors_by_tag',
            'select_actors_in_volume', 'deselect_all', 'get_selected_actors',
            'group_actors', 'ungroup_actors',
            'select_all', 'invert_selection', 'select_children',
            'remove_selected_from_group', 'lock_selected_groups', 'unlock_selected_groups',
            'create_collision_channel', 'create_collision_profile',
            'configure_channel_responses', 'configure_object_type', 'configure_trace_channel',
            'set_actor_collision_profile', 'set_component_collision_profile',
            'get_actor_collision', 'get_component_collision', 'validate_collision_profile',
            'list', 'set_blueprint_variables',
            'create_snapshot',
            'attach', 'attach_actor',
            'detach', 'detach_actor',
            'set_actor_collision', 'call_actor_function'
          ],
          description: 'Action'
        },
        actorName: commonSchemas.actorName,
        childActor: commonSchemas.childActorName,
        parentActor: commonSchemas.parentActorName,
        classPath: commonSchemas.assetPath,
        meshPath: commonSchemas.meshPath,
        blueprintPath: commonSchemas.blueprintPath,
        location: commonSchemas.location,
        rotation: commonSchemas.rotation,
        scale: commonSchemas.scale,
        force: commonSchemas.vector3,
        componentType: commonSchemas.stringProp,
        componentName: commonSchemas.componentName,
        mediaPlayerPath: commonSchemas.assetPath,
        focalLength: commonSchemas.numberProp,
        aperture: commonSchemas.numberProp,
        focusDistance: commonSchemas.numberProp,
        filmbackSensorWidth: commonSchemas.numberProp,
        filmbackSensorHeight: commonSchemas.numberProp,
        properties: commonSchemas.objectProp,
        visible: commonSchemas.visible,
        newName: commonSchemas.newName,
        tag: commonSchemas.tagName,
        volumeActorName: commonSchemas.actorName,
        replaceSelection: commonSchemas.booleanProp,
        selectEvenIfHidden: commonSchemas.booleanProp,
        includeDerivedClasses: commonSchemas.booleanProp,
        recurseChildren: commonSchemas.booleanProp,
        warnIfLevelLocked: commonSchemas.booleanProp,
        variables: commonSchemas.objectProp,
        snapshotName: commonSchemas.stringProp,
        limit: commonSchemas.numberProp,
        filter: commonSchemas.stringProp,
        collisionEnabled: commonSchemas.booleanProp,
        collisionMode: commonSchemas.stringProp,
        profileName: commonSchemas.stringProp,
        channelName: commonSchemas.stringProp,
        channelType: commonSchemas.stringProp,
        objectType: commonSchemas.stringProp,
        traceChannel: commonSchemas.stringProp,
        response: commonSchemas.stringProp,
        defaultResponse: commonSchemas.stringProp,
        responses: commonSchemas.objectProp,
        saveConfig: commonSchemas.booleanProp,
        staticObject: commonSchemas.booleanProp,
        traceType: commonSchemas.booleanProp,
        helpMessage: commonSchemas.stringProp
      },
      required: ['action']
    },
    outputSchema: {
      type: 'object',
      properties: {
        ...commonSchemas.outputWithActor,
        components: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              name: commonSchemas.stringProp,
              class: commonSchemas.stringProp,
              relativeLocation: commonSchemas.location,
              relativeRotation: commonSchemas.rotation,
              relativeScale: commonSchemas.scale
            }
          }
        },
        actors: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              label: commonSchemas.stringProp,
              name: commonSchemas.stringProp,
              path: commonSchemas.stringProp,
              class: commonSchemas.stringProp
            }
          }
        },
        count: commonSchemas.numberProp,
        totalCount: commonSchemas.numberProp,
        isPieWorld: commonSchemas.booleanProp,
        worldName: commonSchemas.stringProp,
        filter: commonSchemas.stringProp,
        data: commonSchemas.nullableObjectProp
      }
    }
  },
  {
    name: 'control_editor',
    category: 'core',
    description: 'Start/stop PIE, control viewport camera, and run bounded automated play-tests with PIE-world validation, screenshots, runtime probes, and guaranteed cleanup.',
    inputSchema: {
      type: 'object',
      properties: {
        action: {
          type: 'string',
          enum: [
            'play', 'start_pie', 'stop', 'stop_pie', 'pause', 'resume', 'eject', 'possess',
            'set_game_speed', 'set_fixed_delta_time',
            'set_camera', 'set_camera_position', 'set_viewport_camera', 'set_camera_fov',
            'set_view_mode', 'set_viewport_resolution',
            'console_command', 'execute_command',
            'screenshot', 'take_screenshot', 'step_frame', 'single_frame_step',
            'start_recording', 'stop_recording', 'play_demo', 'pause_demo', 'seek_demo', 'set_demo_playback_speed', 'configure_killcam_duration', 'start_killcam',
            'open_media', 'play_media', 'pause_media', 'seek_media',
            'start_take_recording', 'stop_take_recording', 'get_take_recording_status',
            'create_bookmark', 'jump_to_bookmark',
            'set_preferences', 'set_viewport_realtime',
            'open_asset', 'close_asset', 'simulate_input',
            'get_pie_state', 'query_pie_actor', 'get_pie_metrics', 'detect_pie_issues',
            'send_input', 'send_enhanced_input', 'move', 'look', 'jump', 'sprint', 'interact',
            'capture_pie_screenshot', 'read_pie_logs', 'run_playtest_sequence',
            'open_level', 'focus_actor',
            'show_stats', 'hide_stats',
            'set_editor_mode', 'set_immersive_mode', 'set_game_view',
            'configure_editor_preferences', 'set_grid_settings', 'set_snap_settings',
            'manage_editor_layouts', 'create_custom_editor_mode',
            'undo', 'redo', 'save_all'
          ],
          description: 'Editor action'
        },
        location: commonSchemas.location,
        rotation: commonSchemas.rotation,
        viewMode: commonSchemas.stringProp,
        enabled: commonSchemas.enabled,
        speed: commonSchemas.numberProp,
        filename: commonSchemas.stringProp,
        fov: commonSchemas.numberProp,
        width: commonSchemas.numberProp,
        height: commonSchemas.numberProp,
        command: commonSchemas.stringProp,
        steps: commonSchemas.integerProp,
        bookmarkName: commonSchemas.stringProp,
        // Path parameters for various actions
        assetPath: commonSchemas.assetPath,
        levelPath: commonSchemas.levelPath,
        path: commonSchemas.directoryPath,
        // Actor-related parameters
        actorName: commonSchemas.actorName,
        name: commonSchemas.name,
        // Action-specific parameters
        mode: { type: 'string', description: 'Editor mode or screenshot source: editor_viewport, game_viewport, full_editor_window, standalone_window.' },
        returnBase64: { type: 'boolean', description: 'Return PNG image data as base64 when supported. Defaults to true for full_editor_window and game_viewport modes.' },
        includeMetadata: commonSchemas.booleanProp,
        metadata: commonSchemas.objectProp,
        demoTime: commonSchemas.numberProp,
        demoSpeed: commonSchemas.numberProp,
        durationSeconds: commonSchemas.numberProp,
        startTime: commonSchemas.numberProp,
        mediaPlayerPath: commonSchemas.assetPath,
        mediaUrl: commonSchemas.stringProp,
        mediaTime: commonSchemas.numberProp,
        sequencePath: commonSchemas.assetPath,
        openSequencer: commonSchemas.booleanProp,
        showErrorMessage: commonSchemas.booleanProp,
        deltaTime: commonSchemas.numberProp,
        resolution: commonSchemas.resolution,
        realtime: commonSchemas.booleanProp,
        stat: commonSchemas.stringProp,
        category: commonSchemas.stringProp,
        preferences: commonSchemas.objectProp,
        gridEnabled: commonSchemas.booleanProp,
        gridSize: commonSchemas.numberProp,
        rotationGridEnabled: commonSchemas.booleanProp,
        scaleGridEnabled: commonSchemas.booleanProp,
        snapToSurface: commonSchemas.booleanProp,
        snapRotation: commonSchemas.booleanProp,
        snapOffsetExtent: commonSchemas.numberProp,
        actorSnapDistance: commonSchemas.numberProp,
        snapDistance: commonSchemas.numberProp,
        actorSnapScale: commonSchemas.numberProp,
        usePowerOf2SnapSize: commonSchemas.booleanProp,
        layoutAction: commonSchemas.stringProp,
        layoutName: commonSchemas.stringProp,
        customModeName: commonSchemas.stringProp,
        customModeId: commonSchemas.stringProp,
        modeDescription: commonSchemas.stringProp,
        key: commonSchemas.stringProp,
        // simulate_input parameters
        type: commonSchemas.stringProp,
        inputType: commonSchemas.stringProp,
        inputAction: commonSchemas.stringProp,
        x: commonSchemas.numberProp,
        y: commonSchemas.numberProp,
        button: commonSchemas.stringProp,
        playerIndex: { type: 'integer', minimum: 0, description: 'PIE local-player/controller index for input dispatch.' },
        axisName: commonSchemas.stringProp,
        axisValue: commonSchemas.numberProp,
        relative: commonSchemas.booleanProp,
        pieMode: { type: 'string', enum: ['viewport', 'new_window', 'standalone'], description: 'PIE destination. Only viewport supports in-process input and runtime validation.' },
        playerStart: commonSchemas.actorName,
        pawnName: commonSchemas.actorName,
        enhancedAction: commonSchemas.stringProp,
        value: commonSchemas.numberProp,
        durationMs: { type: 'number', minimum: 1, maximum: 120000, description: 'Bounded input hold or operation duration in milliseconds.' },
        warmupFrames: { type: 'integer', minimum: 0, maximum: 120, description: 'Frames to render before screenshot capture.' },
        screenshotDelayMs: { type: 'number', minimum: 0, maximum: 5000, description: 'Delay after warm-up before screenshot capture.' },
        captureMode: { type: 'string', enum: ['game_viewport', 'editor_viewport', 'standalone_window'] },
        screenshotPath: { type: 'string', description: 'For standalone_window, a sanitized path relative to Saved/ that identifies an existing PNG written by the standalone game. The editor reads this file; it does not capture another process window.' },
        timeoutMs: { type: 'number', minimum: 1, maximum: 300000, description: 'Client-side deadline for this operation; sent nowhere else.' },
        axisX: commonSchemas.numberProp,
        axisY: commonSchemas.numberProp,
        minMovementCm: commonSchemas.numberProp,
        expectedMovement: commonSchemas.booleanProp,
        previousLocation: commonSchemas.location,
        sequence: { type: 'array', items: { type: 'object', additionalProperties: true }, description: 'Ordered play-test steps. Each step may include assertion: {path, equals|contains|greaterThan|truthy|exists}.' },
        autoStop: commonSchemas.booleanProp,
        saveRuntimeChanges: commonSchemas.booleanProp
      },
      required: ['action']
    },
    outputSchema: {
      type: 'object',
      properties: {
        ...commonSchemas.outputBase,
        imageBase64: commonSchemas.stringProp,
        mimeType: commonSchemas.stringProp,
        width: commonSchemas.numberProp,
        height: commonSchemas.numberProp,
        sizeBytes: commonSchemas.numberProp,
        path: commonSchemas.stringProp,
        screenshotPath: commonSchemas.stringProp,
        mode: commonSchemas.stringProp,
        report: commonSchemas.objectProp,
        summary: commonSchemas.stringProp,
        isInPIE: commonSchemas.booleanProp,
        pieWorld: commonSchemas.stringProp,
        editorWorld: commonSchemas.stringProp,
        actorWorld: commonSchemas.stringProp,
        fps: commonSchemas.numberProp,
        frameTimeMs: commonSchemas.numberProp,
        memoryBytes: commonSchemas.numberProp,
        actorCount: commonSchemas.numberProp
      }
    }
  },
  {
    name: 'manage_level',
    category: 'core',
    description: 'Load/save levels, configure streaming, and build lighting.',
    inputSchema: {
      type: 'object',
      properties: {
        action: {
          type: 'string',
          enum: [
            'load', 'load_level', 'save', 'save_level', 'save_as', 'save_level_as', 'stream', 'unload', 'unload_level', 'create_level', 'create_light', 'build_lighting',
            'set_metadata',
            'export_level', 'import_level', 'list_levels', 'get_summary', 'delete', 'delete_level', 'validate_level',
            'add_sublevel', 'rename_level', 'duplicate_level', 'get_current_level'
          ],
          description: 'Action'
        },
        // Level path parameters
        levelPath: commonSchemas.levelPath,
        assetPath: commonSchemas.assetPath,
        levelPaths: commonSchemas.arrayOfStrings,
        levelName: commonSchemas.stringProp,
        name: commonSchemas.name,
        path: commonSchemas.directoryPathForCreation,
        // Save/export/import paths
        savePath: commonSchemas.savePath,
        destinationPath: commonSchemas.destinationPath,
        overwrite: commonSchemas.overwrite,
        targetPath: commonSchemas.directoryPath,
        exportPath: commonSchemas.exportPath,
        packagePath: commonSchemas.directoryPath,
        sourcePath: commonSchemas.sourcePath,
        // Sublevel parameters
        sublevelPath: commonSchemas.levelPath,
        subLevelPath: commonSchemas.levelPath,
        parentLevel: commonSchemas.parentLevel,
        parentPath: commonSchemas.directoryPath,
        streamingMethod: commonSchemas.stringProp,
        // Streaming control
        streaming: commonSchemas.booleanProp,
        shouldBeLoaded: commonSchemas.booleanProp,
        shouldBeVisible: commonSchemas.booleanProp,
        saveDirtyPackages: commonSchemas.booleanProp,
        // Light creation
        lightType: { type: 'string', enum: ['Directional', 'Point', 'Spot', 'Rect', 'DirectionalLight', 'PointLight', 'SpotLight', 'RectLight', 'directional', 'point', 'spot', 'rect'], description: 'Light type. Accepts short names (Point), class names (PointLight), or lowercase (point).' },
        quality: commonSchemas.stringProp,
        intensity: commonSchemas.numberProp,
        color: commonSchemas.color,
        location: commonSchemas.location,
        rotation: commonSchemas.rotation,
        // Level creation
        template: commonSchemas.stringProp,
        useWorldPartition: commonSchemas.booleanProp,
        // Metadata & utilities
        metadata: commonSchemas.objectProp,
        newName: commonSchemas.stringProp,
        timeoutMs: commonSchemas.numberProp
      },
      required: ['action']
    },
    outputSchema: {
      type: 'object',
      properties: {
        ...commonSchemas.outputBase,
        assetPath: commonSchemas.assetPath,
        emitterName: commonSchemas.stringProp,
        moduleName: commonSchemas.stringProp,
        niagaraInfo: commonSchemas.objectProp,
        validationResult: commonSchemas.objectProp
      }
    }
  },
  {
    name: 'system_control',
    category: 'core',
    description: 'Control the project runtime: profiling, benchmarks, scalability/LOD/Nanite settings, CVars, console commands, Python scripts, Unreal subsystems, timers, latent actions, async work, gameplay tasks, UBT, tests, logs, and widgets.',
    inputSchema: {
      type: 'object',
      properties: {
        action: {
          type: 'string',
          enum: [
            'get_game_instance', 'get_game_mode', 'get_game_state', 'get_num_player_controllers', 'get_num_player_states', 'get_targeting_subsystem', 'get_closest_listener_location',
            'profile', 'show_fps', 'set_quality', 'set_quality_level', 'set_world_rendering', 'set_global_time_dilation', 'set_global_pitch_modulation', 'set_force_disable_splitscreen', 'set_game_paused', 'is_game_paused', 'get_audio_time_seconds', 'get_accurate_real_time', 'get_time_seconds', 'get_unpaused_time_seconds', 'get_real_time_seconds', 'get_world_delta_seconds', 'get_current_level_name', 'get_current_reverb_effect', 'get_player_controller', 'get_player_pawn', 'get_player_character', 'get_player_camera_manager', 'get_player_state', 'get_viewport_mouse_capture_mode', 'set_viewport_mouse_capture_mode', 'is_any_local_player_camera_within_range', 'get_num_local_player_controllers', 'set_subtitles_enabled', 'are_subtitles_enabled', 'get_available_spatial_plugins', 'get_active_spatial_plugin', 'set_active_spatial_plugin', 'get_platform_name', 'set_max_audio_channels_scaled', 'get_max_audio_channel_count', 'are_any_listeners_within_range', 'configure_scalability_group', 'screenshot', 'set_resolution', 'set_fullscreen', 'execute_command', 'console_command',
            'run_ubt', 'run_uat', 'validate_release', 'validate_project', 'validate_blueprints', 'start_memory_report', 'configure_stat_commands', 'configure_console_variables', 'check_for_errors', 'capture_insights_trace', 'analyze_trace', 'start_network_profiler', 'enable_visual_logger', 'add_visual_log_entry', 'inspect_platform_capabilities', 'sign_release', 'run_packaged', 'deploy_package', 'run_network_soak', 'manage_project_plugin', 'get_job_status', 'list_jobs', 'cancel_job', 'read_project_file', 'write_project_file', 'generate_save_game_class', 'configure_checkpoint_data', 'create_automation_test', 'get_test_results', 'list_gameplay_tags', 'get_runtime_gameplay_tag', 'add_gameplay_tag', 'remove_gameplay_tag', 'list_config_layers', 'get_config_value', 'read_config_value', 'set_config_value', 'write_config_value', 'get_section', 'create_config_section', 'reload_config', 'flush_config', 'get_config_hierarchy', 'save_game_to_slot', 'load_game_from_slot', 'save_game_to_memory', 'load_game_from_memory', 'save_data_to_slot', 'load_data_from_slot', 'save_checkpoint_async', 'load_checkpoint_async', 'inspect_save_game_schema', 'delete_save_game_slot', 'check_save_game_slot', 'list_save_game_slots', 'run_tests', 'subscribe', 'unsubscribe', 'spawn_category', 'enable_gameplay_debugger', 'start_session', 'stop_session', 'get_session_status', 'check_map_errors', 'create_functional_test', 'runtime_health', 'get_runtime_capabilities', 'get_runtime_world', 'get_runtime_actors', 'get_runtime_actor', 'lumen_update_scene',
            'wait_for_job', 'cook_content', 'package_project', 'create_string_table', 'add_string_entry', 'get_localized_string', 'create_gameplay_tag', 'create_asset_validator', 'run_data_validation', 'list_plugins', 'enable_plugin', 'disable_plugin', 'get_plugin_status',
            'enable_photo_mode', 'configure_photo_mode_ui', 'play_sound', 'create_widget', 'show_widget', 'add_widget_child',
            'set_cvar', 'get_project_settings', 'validate_assets',
            'set_project_setting', 'release_gate',
            'create_game_instance_subsystem', 'create_world_subsystem',
            'create_local_player_subsystem', 'create_engine_subsystem',
            'configure_subsystem_tick', 'get_subsystem', 'inspect_subsystem',
            'list_subsystems',
            'set_timer', 'clear_timer', 'pause_timer', 'resume_timer', 'get_timer', 'list_timers',
            'create_latent_action', 'clear_latent_action', 'get_latent_action', 'list_latent_actions',
            'create_async_action', 'cancel_async_action', 'get_async_action', 'list_async_actions',
            'create_gameplay_task', 'end_gameplay_task', 'get_gameplay_task', 'list_gameplay_tasks',
            'create_tag_container', 'add_tag_to_container', 'remove_tag_from_container', 'check_tag_match',
            'configure_task_priority',
            'create_event_dispatcher', 'bind_to_event', 'unbind_from_event', 'broadcast_event',
            'create_delegate', 'bind_delegate', 'inspect_delegate', 'list_delegate_bindings',
            'create_blueprint_interface', 'add_interface_function', 'implement_interface',
            'get_interface_info', 'call_interface_function', 'generate_project_files', 'set_language_and_locale', 'set_locale', 'register_native_tag'
          ],
          description: 'Action'
        },
        profileType: commonSchemas.stringProp,
        category: commonSchemas.stringProp,
        level: commonSchemas.numberProp,
        group: commonSchemas.stringProp,
        enabled: commonSchemas.enabled,
        timeDilation: commonSchemas.numberProp,
        pitchModulation: commonSchemas.numberProp,
        timeSec: commonSchemas.numberProp,
        disableSplitscreen: commonSchemas.booleanProp,
        paused: commonSchemas.booleanProp,
        maxChannelCountScale: commonSchemas.numberProp,
        location: commonSchemas.location,
        maximumRange: commonSchemas.numberProp,
        resolution: commonSchemas.resolution,
        command: commonSchemas.stringProp,
        target: commonSchemas.stringProp,
        platform: commonSchemas.stringProp,
        configuration: commonSchemas.stringProp,
        arguments: commonSchemas.stringProp,
        async: { type: 'boolean', description: 'For run_ubt, return a jobId immediately and poll with jobId.' },
        jobId: commonSchemas.stringProp,
        uatOperation: { type: 'string', enum: ['build', 'cook', 'stage', 'package', 'archive', 'build_cook_stage_package', 'build_server', 'package_server', 'archive_server'] },
        server: commonSchemas.booleanProp,
        serverConfiguration: commonSchemas.stringProp,
        archiveDirectory: commonSchemas.outputPath,
        requiredFiles: commonSchemas.arrayOfStrings,
        requiredDirectories: commonSchemas.arrayOfStrings,
        projectRequiredFiles: commonSchemas.arrayOfStrings,
        projectRequiredDirectories: commonSchemas.arrayOfStrings,
        includeInventory: { type: 'boolean', description: 'Include a bounded project content/config/map inventory in validation results. Defaults to true.' },
        validationMode: { type: 'string', enum: ['static', 'data_validation'], description: 'Validation depth. data_validation launches UnrealEditor-Cmd with the DataValidation commandlet and returns a managed job.' },
        validationArguments: commonSchemas.arrayOfStrings,
        timeoutMs: commonSchemas.numberProp,
        reportPath: { type: 'string', description: 'Optional JSON report filename written under Saved/AutomationReports after run_tests completes.' },
        testName: commonSchemas.name,
        timeLimit: { type: 'number', minimum: 0, maximum: 3600, description: 'Optional Functional Test time limit in seconds.' },
        actorName: commonSchemas.actorName,
        classFilter: commonSchemas.stringProp,
        limit: commonSchemas.integerProp,
        saveLevel: { type: 'boolean', description: 'Persist the newly created Functional Test actor to the loaded level.' },
        pluginAction: { type: 'string', enum: ['list', 'validate', 'enable', 'disable'] },
        pluginName: commonSchemas.name,
        platformName: commonSchemas.stringProp,
        removePrefixString: commonSchemas.booleanProp,
        mouseCaptureMode: { type: 'string', enum: ['NoCapture', 'CapturePermanently', 'CapturePermanently_IncludingInitialMouseDown', 'CaptureDuringMouseDown', 'CaptureDuringRightMouseDown'] },
        requirePak: commonSchemas.booleanProp,
        manifestPath: { type: 'string', description: 'Optional release JSON manifest inside archiveDirectory mapping files to SHA-256 hashes.' },
        compressed: commonSchemas.booleanProp,
        encryptIniFiles: commonSchemas.booleanProp,
        encryptPakIndex: commonSchemas.booleanProp,
        includePrerequisites: commonSchemas.booleanProp,
        runProjectValidation: commonSchemas.booleanProp,
        runPackagedSmoke: commonSchemas.booleanProp,
        packagedArtifactPath: commonSchemas.stringProp,
        runAutomationTests: { type: 'boolean', description: 'When used with release_gate, run Unreal automation tests and fail the gate on test failure.' },
        validatePlugins: commonSchemas.booleanProp,
        filePath: commonSchemas.stringProp,
        projectPath: commonSchemas.stringProp,
        enginePath: commonSchemas.stringProp,
        artifactPath: commonSchemas.stringProp,
        certificatePath: commonSchemas.stringProp,
        signingIdentity: commonSchemas.stringProp,
        keystorePath: commonSchemas.stringProp,
        signingAlias: commonSchemas.stringProp,
        signingPasswordEnv: commonSchemas.stringProp,
        deviceId: commonSchemas.stringProp,
        paths: commonSchemas.arrayOfStrings,
        recursive: commonSchemas.booleanProp,
        maxAssets: commonSchemas.numberProp,
        saveAfterCompile: commonSchemas.booleanProp,
        statNames: commonSchemas.arrayOfStrings,
        logCategories: commonSchemas.arrayOfStrings,
        tracePath: commonSchemas.stringProp,
        visualLogText: { type: 'string', maxLength: 4096 },
        visualLogCategory: commonSchemas.stringProp,
        serverArtifactPath: commonSchemas.stringProp,
        clientArtifactPath: commonSchemas.stringProp,
        serverArguments: commonSchemas.stringProp,
        clientArguments: commonSchemas.stringProp,
        clientCount: commonSchemas.numberProp,
        serverPort: commonSchemas.numberProp,
        durationMs: commonSchemas.numberProp,
        serverStartupTimeoutMs: commonSchemas.numberProp,
        clientStartupTimeoutMs: commonSchemas.numberProp,
        serverReadyPattern: { type: 'string', maxLength: 256, description: 'Optional literal/regex text expected in the dedicated server output before clients launch.' },
        clientReadyPattern: { type: 'string', maxLength: 256, description: 'Optional literal/regex text each packaged client must emit before the soak is considered started.' },
        dryRun: commonSchemas.booleanProp,
        content: { type: 'string', maxLength: 1048576 },
        backup: commonSchemas.booleanProp,
        className: commonSchemas.name,
        headerPath: commonSchemas.stringProp,
        sourcePath: commonSchemas.stringProp,
        variables: commonSchemas.arrayOfObjects,
        schemaVersion: commonSchemas.numberProp,
        migrationManifestPath: commonSchemas.stringProp,
        migrations: commonSchemas.arrayOfObjects,
        tag: commonSchemas.tagName,
        comment: commonSchemas.stringProp,
        saveGameObject: commonSchemas.stringProp,
        dataBase64: commonSchemas.stringProp,
        slotName: commonSchemas.name,
        userIndex: commonSchemas.numberProp,
        filter: commonSchemas.stringProp,
        channels: commonSchemas.stringProp,
        widgetPath: commonSchemas.widgetPath,
        childClass: commonSchemas.stringProp,
        parentName: commonSchemas.stringProp,
        section: commonSchemas.stringProp,
        key: commonSchemas.stringProp,
        value: commonSchemas.stringProp,
        stringTableId: commonSchemas.stringProp,
        namespace: commonSchemas.stringProp,
        stringKey: commonSchemas.stringProp,
        sourceString: commonSchemas.stringProp,
        devNotes: commonSchemas.stringProp,
        culture: commonSchemas.stringProp,
        configName: commonSchemas.stringProp,
        mode: screenshotModeSchema,
        returnBase64: { type: 'boolean', description: 'Return PNG image data as base64 when supported. Defaults to true for full_editor_window and game_viewport screenshot modes.' },
        includeMetadata: commonSchemas.booleanProp,
        metadata: commonSchemas.objectProp,
        subsystemClass: commonSchemas.stringProp,
        subsystemName: commonSchemas.stringProp,
        subsystemScope: commonSchemas.stringProp,
        worldContext: commonSchemas.stringProp,
        playerIndex: commonSchemas.numberProp,
        tickType: commonSchemas.stringProp,
        tickEnabled: commonSchemas.booleanProp,
        timerId: commonSchemas.stringProp,
        rate: commonSchemas.numberProp,
        firstDelay: commonSchemas.numberProp,
        looping: commonSchemas.booleanProp,
        callbackObject: commonSchemas.stringProp,
        callbackFunction: commonSchemas.stringProp,
        latentId: commonSchemas.stringProp,
        uuid: commonSchemas.numberProp,
        linkage: commonSchemas.numberProp,
        asyncId: commonSchemas.stringProp,
        execution: commonSchemas.stringProp,
        label: commonSchemas.stringProp,
        taskId: commonSchemas.stringProp,
        ownerObject: commonSchemas.stringProp,
        instanceName: commonSchemas.stringProp,
        priority: commonSchemas.numberProp,
        activate: commonSchemas.booleanProp,
        taskType: commonSchemas.stringProp
        ,name: commonSchemas.name
        ,blueprintPath: commonSchemas.assetPath
        ,folder: commonSchemas.assetPath
        ,delegateObject: commonSchemas.stringProp
        ,delegateName: commonSchemas.name
        ,delegateKind: { type: 'string', enum: ['single', 'multicast', 'event_dispatcher'] }
        ,targetObject: commonSchemas.stringProp
        ,functionName: commonSchemas.name
        ,interfacePath: commonSchemas.assetPath
        ,interfaceClass: commonSchemas.stringProp
        ,interfaceFunction: commonSchemas.name
        ,interfaceFunctionName: commonSchemas.name
        ,parameterValues: commonSchemas.objectProp
        ,saveAsset: commonSchemas.booleanProp
      },
      required: ['action']
    },
    outputSchema: {
      type: 'object',
      properties: {
        ...commonSchemas.outputBase,
        output: commonSchemas.stringProp,
        imageBase64: commonSchemas.stringProp,
        mimeType: commonSchemas.stringProp,
        width: commonSchemas.numberProp,
        height: commonSchemas.numberProp,
        sizeBytes: commonSchemas.numberProp,
        path: commonSchemas.stringProp,
        screenshotPath: commonSchemas.stringProp,
        mode: commonSchemas.stringProp
      }
    }
  },
  {
    name: 'inspect',
    category: 'core',
    description: 'Inspect any UObject: read/write properties, list components, export snapshots, and query class info. Actions: inspect_cdo (Blueprint CDO properties + all components without spawning an actor; use blueprintPath, optional detailed/componentName/propertyNames), inspect_class (class metadata), inspect_object (world actor), get_property/set_property, get_components, list_objects, find_by_class, find_by_tag, runtime_report, production_capabilities.',
    inputSchema: {
      type: 'object',
      properties: {
        action: {
          type: 'string',
          enum: [
            'inspect_object', 'get_actor_details', 'get_blueprint_details', 'get_mesh_details',
            'get_texture_details', 'get_material_details', 'get_level_details', 'get_component_details',
            'set_property', 'get_property',
            'get_components', 'get_component_property', 'set_component_property',
            'inspect_class', 'inspect_cdo', 'runtime_report', 'pie_report', 'production_capabilities', 'list_objects',
            'get_metadata', 'add_tag', 'find_by_tag',
            'create_snapshot', 'restore_snapshot', 'export', 'delete_object', 'find_by_class', 'get_bounding_box',
            'get_project_settings', 'get_world_settings', 'get_viewport_info', 'get_selected_actors',
            'get_scene_stats', 'get_performance_stats', 'get_memory_stats', 'get_editor_settings'
          ],
          description: 'Action'
        },
        objectPath: commonSchemas.assetPath,
        propertyName: commonSchemas.propertyName,
        propertyPath: commonSchemas.stringProp,
        value: commonSchemas.value,
        actorName: commonSchemas.actorName,
        name: commonSchemas.name,
        componentName: commonSchemas.componentName,
        className: commonSchemas.stringProp,
        classPath: commonSchemas.assetPath,
        tag: commonSchemas.tagName,
        filter: commonSchemas.stringProp,
        snapshotName: commonSchemas.stringProp,
        blueprintPath: commonSchemas.blueprintPath,
        detailed: commonSchemas.booleanProp,
        propertyNames: commonSchemas.arrayOfStrings,
        componentNames: commonSchemas.arrayOfStrings
      },
      required: ['action']
    },
    outputSchema: {
      type: 'object',
      properties: {
        ...commonSchemas.outputBase,
        value: commonSchemas.value,
        blueprintPath: commonSchemas.blueprintPath,
        className: commonSchemas.stringProp,
        classPath: commonSchemas.stringProp,
        parentClass: commonSchemas.stringProp,
        cdoProperties: commonSchemas.objectProp,
        components: commonSchemas.arrayOfObjects,
        componentCount: commonSchemas.numberProp,
        componentName: commonSchemas.componentName,
        templateObjectName: commonSchemas.stringProp,
        componentClass: commonSchemas.stringProp,
        count: commonSchemas.numberProp,
        objects: commonSchemas.arrayOfObjects,
        actors: commonSchemas.arrayOfObjects
      }
    }
  }
];

addActionParamsSchema(coreToolDefinitions);
