// McpTool_SystemControl.cpp — system_control tool definition

#include "McpVersionCompatibility.h"
#include "MCP/McpToolDefinition.h"
#include "MCP/McpToolRegistry.h"
#include "MCP/McpSchemaBuilder.h"
#include "MCP/McpConsolidatedActionRouting.h"

class FMcpTool_SystemControl : public FMcpToolDefinition
{
public:
	FString GetName() const override { return TEXT("system_control"); }

	FString GetDescription() const override
	{
		return TEXT("Run profiling, set quality/CVars, execute console commands, "
			"execute Python scripts, manage Unreal subsystems, timers, async work, and gameplay tasks, "
			"run UBT, manage widgets, delegates, Blueprint interfaces, and take screenshots.");
	}

	FString GetCategory() const override { return TEXT("core"); }

	TSharedPtr<FJsonObject> BuildInputSchema() const override
	{
		return FMcpSchemaBuilder()
			.StringEnum(TEXT("action"), McpConsolidatedActions::SystemControl(),
				TEXT("Action"))
			.StringEnum(TEXT("type"), {
				TEXT("CPU"),
				TEXT("GPU"),
				TEXT("Memory"),
				TEXT("RenderThread"),
				TEXT("GameThread"),
				TEXT("All")
			}, TEXT("Profiling or benchmark type."))
			.String(TEXT("profileType"), TEXT(""))
			.String(TEXT("category"), TEXT(""))
			.Number(TEXT("level"), TEXT(""))
			.Bool(TEXT("enabled"), TEXT("Whether the item/feature is enabled."))
			.String(TEXT("resolution"), TEXT("Resolution setting (e.g., 1024x1024)."))
			.String(TEXT("command"), TEXT(""))
			.String(TEXT("profileName"), TEXT("Device profile identifier."))
			.String(TEXT("profileType"), TEXT("Device type such as Win64, IOS, or Android."))
			.String(TEXT("parentProfileName"), TEXT("Optional base device profile."))
			.Object(TEXT("cvars"), TEXT("Scalar CVar overrides for the device profile."))
			.StringEnum(TEXT("shaderMode"), { TEXT("changed"), TEXT("all") }, TEXT("Shader recompilation scope."))
			.String(TEXT("target"), TEXT(""))
			.String(TEXT("platform"), TEXT(""))
			.String(TEXT("configuration"), TEXT(""))
			.String(TEXT("arguments"), TEXT(""))
			.Bool(TEXT("async"), TEXT("For SaveGame and host operations, return a lifecycle identifier instead of waiting."))
			.String(TEXT("jobId"), TEXT("Managed host job identifier."))
			.String(TEXT("uatOperation"), TEXT("RunUAT BuildCookRun operation."))
			.Bool(TEXT("server"), TEXT("Build a dedicated server/no-client target."))
			.String(TEXT("serverConfiguration"), TEXT("Dedicated server configuration."))
			.String(TEXT("archiveDirectory"), TEXT("Archive output directory."))
			.String(TEXT("projectName"), TEXT("Project architecture manifest name."))
			.Array(TEXT("requirements"), TEXT("Architecture requirements with id, kind, path, description, and required fields."))
			.Object(TEXT("requirement"), TEXT("Single architecture requirement object."))
			.String(TEXT("requirementId"), TEXT("Architecture requirement identifier."))
			.String(TEXT("requirementKind"), TEXT("Architecture requirement kind."))
			.String(TEXT("requirementPath"), TEXT("Project-relative file or directory path for an architecture requirement."))
			.String(TEXT("description"), TEXT("Architecture requirement description."))
			.Bool(TEXT("required"), TEXT("Whether the architecture requirement is release-blocking."))
			.Bool(TEXT("replaceExisting"), TEXT("Replace an existing architecture requirement with the same id."))
			.Bool(TEXT("includeOptional"), TEXT("Validate optional architecture requirements too."))
			.Bool(TEXT("compressed"), TEXT("Compress staged/package output."))
			.Bool(TEXT("encryptIniFiles"), TEXT("Encrypt packaged INI files."))
			.Bool(TEXT("encryptPakIndex"), TEXT("Encrypt the PAK index."))
			.Bool(TEXT("includePrerequisites"), TEXT("Include platform prerequisites in packaged output."))
			.Bool(TEXT("runProjectValidation"), TEXT("Run static project validation as part of release_gate."))
			.Bool(TEXT("runPackagedSmoke"), TEXT("Launch packagedArtifactPath through the host-managed release smoke gate."))
			.String(TEXT("packagedArtifactPath"), TEXT("Packaged executable used by the release smoke gate."))
			.Bool(TEXT("runAutomationTests"), TEXT("Run Unreal automation tests as part of release_gate."))
			.Bool(TEXT("validatePlugins"), TEXT("Validate declared project plugin dependencies as part of release_gate."))
			.String(TEXT("filePath"), TEXT("Relative path inside the Unreal project."))
			.Array(TEXT("requiredDirectories"), TEXT("Relative directories required in the project."))
			.Array(TEXT("projectRequiredFiles"), TEXT("Relative project files required by release_gate project validation."))
			.Array(TEXT("projectRequiredDirectories"), TEXT("Relative project directories required by release_gate project validation."))
			.String(TEXT("architectureManifestPath"), TEXT("Project-relative architecture manifest used by release_gate."))
			.Bool(TEXT("validateArchitecture"), TEXT("Validate the project architecture manifest as part of release_gate."))
			.Bool(TEXT("includeInventory"), TEXT("Include a bounded project content/config/map inventory."))
			.StringEnum(TEXT("validationMode"), { TEXT("static"), TEXT("data_validation") }, TEXT("Validation depth; data_validation runs UnrealEditor-Cmd DataValidation."))
			.Array(TEXT("validationArguments"), TEXT("Additional validated DataValidation commandlet tokens."))
			.Number(TEXT("timeoutMs"), TEXT("Maximum host validation job duration in milliseconds."))
			.Number(TEXT("pollIntervalMs"), TEXT("Bounded polling interval for wait_for_async_action."))
			.StringEnum(TEXT("pluginAction"), { TEXT("list"), TEXT("validate"), TEXT("enable"), TEXT("disable") }, TEXT("Project plugin operation."))
			.String(TEXT("pluginName"), TEXT("Declared project plugin identifier."))
			.String(TEXT("enginePath"), TEXT("Optional Unreal Engine root used for capability discovery."))
			.String(TEXT("artifactPath"), TEXT("Release artifact to sign, confined to the project or archive directory."))
			.String(TEXT("certificatePath"), TEXT("Windows signing certificate path."))
			.String(TEXT("signingIdentity"), TEXT("Platform signing identity or certificate thumbprint."))
			.String(TEXT("keystorePath"), TEXT("Android signing keystore path."))
			.String(TEXT("signingAlias"), TEXT("Android signing key alias."))
			.String(TEXT("signingPasswordEnv"), TEXT("Environment variable containing the Android signing password."))
			.String(TEXT("deviceId"), TEXT("Android device serial or iOS/tvOS simulator identifier for local deployment."))
			.String(TEXT("serverArtifactPath"), TEXT("Packaged server executable for a host-controlled network soak."))
			.String(TEXT("clientArtifactPath"), TEXT("Packaged client executable for a host-controlled network soak."))
			.String(TEXT("serverArguments"), TEXT("Validated arguments for the packaged server."))
			.String(TEXT("clientArguments"), TEXT("Validated arguments for each packaged client."))
			.Number(TEXT("clientCount"), TEXT("Number of packaged clients to launch, bounded to 1-32."))
			.Number(TEXT("serverPort"), TEXT("Managed local server port, bounded to 1024-65535."))
			.Number(TEXT("durationMs"), TEXT("Bounded soak duration in milliseconds."))
			.Number(TEXT("serverStartupTimeoutMs"), TEXT("Bounded wait for a packaged server readiness signal."))
			.Number(TEXT("clientStartupTimeoutMs"), TEXT("Bounded wait for each packaged client readiness signal."))
			.String(TEXT("serverReadyPattern"), TEXT("Optional server output pattern required before clients launch."))
			.String(TEXT("clientReadyPattern"), TEXT("Optional output pattern each packaged client must emit before the soak is considered started."))
			.Array(TEXT("paths"), TEXT("Blueprint assets or directories to validate; defaults to /Game."))
			.Bool(TEXT("recursive"), TEXT("Recursively scan selected Blueprint directories."))
			.Number(TEXT("maxAssets"), TEXT("Maximum number of Blueprints to compile in one validation request."))
			.Bool(TEXT("saveAfterCompile"), TEXT("Save successfully compiled Blueprints."))
			.Array(TEXT("statNames"), TEXT("Allowlisted Unreal stat names to enable or disable."))
			.Array(TEXT("logCategories"), TEXT("Unreal message-log categories to inspect for errors and warnings."))
			.String(TEXT("tracePath"), TEXT("Safe .utrace filename stored under the project Saved/Profiling/Traces directory."))
			.String(TEXT("visualLogText"), TEXT("Bounded text to add to the Visual Logger."))
			.String(TEXT("visualLogCategory"), TEXT("Visual Logger category name."))
			.Bool(TEXT("dryRun"), TEXT("Validate and return the signing or deployment command without executing it."))
			.String(TEXT("content"), TEXT("Project file content."))
			.Bool(TEXT("backup"), TEXT("Create a .bak file before replacement."))
			.String(TEXT("className"), TEXT("U-prefixed SaveGame class name."))
			.String(TEXT("headerPath"), TEXT("Relative SaveGame header path."))
			.String(TEXT("sourcePath"), TEXT("Relative SaveGame source path."))
			.Array(TEXT("variables"), TEXT("SaveGame variables with name, type, and optional defaultValue."))
			.Number(TEXT("schemaVersion"), TEXT("Optional SaveGame schema version."))
			.String(TEXT("migrationManifestPath"), TEXT("Optional project-relative SaveGame migration manifest path."))
			.Array(TEXT("migrations"), TEXT("SaveGame migration edges with fromVersion, toVersion, and description."))
			.String(TEXT("tag"), TEXT("Gameplay Tag name."))
			.Array(TEXT("tags"), TEXT("Gameplay tag names used to build a transient FGameplayTagContainer."))
			.Array(TEXT("matchTags"), TEXT("Gameplay tag names used as the match container."))
			.StringEnum(TEXT("matchMode"), { TEXT("any"), TEXT("all"), TEXT("any_exact"), TEXT("all_exact") }, TEXT("Gameplay tag matching mode."))
			.String(TEXT("stringTableId"), TEXT("Transient string table registry identifier."))
			.String(TEXT("namespace"), TEXT("Optional string table namespace."))
			.String(TEXT("stringKey"), TEXT("String table entry key."))
			.String(TEXT("sourceString"), TEXT("String table source text."))
			.String(TEXT("devNotes"), TEXT("Optional string table developer notes."))
			.String(TEXT("culture"), TEXT("Culture or language/locale tag to set as an IETF language tag, for example en-US."))
			.Number(TEXT("level"), TEXT("Scalability quality level: 0 low, 1 medium, 2 high, 3 epic, 4 cinematic."))
			.String(TEXT("group"), TEXT("Scalability group name, for example Shadow, Texture, Effects, or ViewDistance."))
			.String(TEXT("comment"), TEXT("Gameplay Tag developer comment."))
			.String(TEXT("configName"), TEXT("Safe Unreal Config filename, for example DefaultGame.ini."))
			.String(TEXT("section"), TEXT("INI section name."))
			.String(TEXT("key"), TEXT("INI key name."))
			.String(TEXT("saveGameObject"), TEXT("Loaded USaveGame object path to save."))
			.String(TEXT("slotName"), TEXT("Safe SaveGame slot identifier."))
			.Number(TEXT("userIndex"), TEXT("SaveGame local user index."))
			.Array(TEXT("requiredFiles"), TEXT("Relative files required in the release archive."))
			.Bool(TEXT("requirePak"), TEXT("Require at least one .pak file in the release archive."))
			.String(TEXT("filter"), TEXT(""))
			.String(TEXT("channels"), TEXT(""))
			.String(TEXT("subAction"), TEXT("Insights session operation: start_session, stop_session, or get_session_status."))
			.String(TEXT("testName"), TEXT("Functional Test actor name."))
			.Bool(TEXT("enabled"), TEXT("Whether the Functional Test is enabled."))
			.Number(TEXT("timeLimit"), TEXT("Functional Test time limit in seconds (0-3600)."))
			.Bool(TEXT("saveLevel"), TEXT("Persist the newly created Functional Test actor to the loaded level."))
			.String(TEXT("widgetPath"), TEXT("Widget blueprint path."))
			.String(TEXT("childClass"), TEXT(""))
			.String(TEXT("parentName"), TEXT(""))
			// section/key are declared above for config hierarchy actions.
			.String(TEXT("value"), TEXT(""))
			.String(TEXT("code"), TEXT("Python code to execute inline"))
			.String(TEXT("file"), TEXT("Path to .py file to execute"))
			.Number(TEXT("duration"), TEXT("Duration in seconds."))
			.String(TEXT("outputPath"), TEXT("Output file or directory path."))
			.Bool(TEXT("detailed"), TEXT("Whether to include detailed output."))
			.Number(TEXT("scale"), TEXT("Resolution scale or percentage."))
			.Number(TEXT("maxFPS"), TEXT("Frame rate limit."))
			.Number(TEXT("poolSize"), TEXT("Texture streaming pool size in MB."))
			.Bool(TEXT("boostPlayerLocation"), TEXT("Whether to boost streaming around the player location."))
			.Number(TEXT("forceLOD"), TEXT("Forced LOD index."))
			.Number(TEXT("lodBias"), TEXT("LOD bias."))
			.Bool(TEXT("enableInstancing"), TEXT("Whether to enable instancing."))
			.Bool(TEXT("enableBatching"), TEXT("Whether to enable batching."))
			.Bool(TEXT("mergeActors"), TEXT("Whether to merge source actors."))
			.Array(TEXT("actors"), TEXT("Actor names."))
			.Number(TEXT("streamingDistance"), TEXT("World Partition streaming distance."))
			.Number(TEXT("cellSize"), TEXT("World Partition cell size."))
			.String(TEXT("packageName"), TEXT("Package name or asset path."))
			.String(TEXT("assetPath"), TEXT("Asset path to validate."))
			.String(TEXT("path"), TEXT("Asset or directory path to validate."))
			.Array(TEXT("paths"), TEXT("Asset or directory paths to validate."))
			.Bool(TEXT("recursive"), TEXT("Whether directory validation counts assets recursively."))
			.Bool(TEXT("replaceSourceActors"), TEXT("Whether to replace source actors after merge."))
			.String(TEXT("filename"), TEXT("Screenshot filename."))
			.String(TEXT("mode"), TEXT("Screenshot source: editor_viewport, game_viewport, full_editor_window."))
			.Bool(TEXT("returnBase64"), TEXT("Return PNG image data as base64 when supported. Defaults to true for full_editor_window and game_viewport modes."))
			.Bool(TEXT("includeMetadata"), TEXT("Attach caller-provided metadata to the response."))
			.FreeformObject(TEXT("metadata"), TEXT("Caller-provided screenshot metadata."))
			.String(TEXT("subsystemClass"), TEXT("Subsystem class path, for example /Script/Engine.WorldPartitionSubsystem."))
			.String(TEXT("subsystemName"), TEXT("Subsystem class name alias."))
			.String(TEXT("subsystemScope"), TEXT("engine, game_instance, world, local_player, or editor."))
			.String(TEXT("worldContext"), TEXT("auto, pie, or editor when resolving world-owned subsystems."))
			.Number(TEXT("playerIndex"), TEXT("Local player index for local-player subsystems."))
			.String(TEXT("tickType"), TEXT("conditional, always, or never for tickable world subsystems."))
			.Bool(TEXT("tickEnabled"), TEXT("Enable or disable ticking for a tickable world subsystem."))
			.String(TEXT("timerId"), TEXT("Managed timer identifier."))
			.Number(TEXT("rate"), TEXT("Timer interval in seconds."))
			.Number(TEXT("firstDelay"), TEXT("Initial timer delay in seconds."))
			.Bool(TEXT("looping"), TEXT("Repeat the timer after each interval."))
			.String(TEXT("callbackObject"), TEXT("Loaded UObject path for an optional zero-argument callback."))
			.String(TEXT("callbackFunction"), TEXT("Optional zero-argument UFunction to invoke when a timer or latent action completes."))
			.String(TEXT("latentId"), TEXT("Managed latent-action identifier."))
			.Number(TEXT("uuid"), TEXT("Latent action UUID; generated when omitted."))
			.Number(TEXT("linkage"), TEXT("Latent callback linkage value."))
			.String(TEXT("asyncId"), TEXT("Managed async-action identifier."))
			.String(TEXT("execution"), TEXT("Async execution mode: task_graph, task_graph_main_thread, task_graph_main_tick, thread, thread_pool, or large_thread_pool."))
			.String(TEXT("label"), TEXT("Optional label for an async action."))
			.String(TEXT("taskId"), TEXT("Managed gameplay-task identifier."))
			.String(TEXT("ownerObject"), TEXT("Loaded UObject path implementing a gameplay-task owner."))
			.String(TEXT("instanceName"), TEXT("Gameplay task instance name."))
			.Number(TEXT("priority"), TEXT("Gameplay task priority from 0 to 255."))
			.Bool(TEXT("activate"), TEXT("Activate the gameplay task immediately; defaults to true."))
			.String(TEXT("taskType"), TEXT("Managed task type; currently generic is supported."))
			.String(TEXT("blueprintPath"), TEXT("Blueprint asset path for delegate or interface authoring."))
			.String(TEXT("folder"), TEXT("Content folder for a newly created Blueprint Interface."))
			.String(TEXT("delegateObject"), TEXT("Loaded UObject path containing the reflected delegate property."))
			.String(TEXT("delegateName"), TEXT("Delegate or event-dispatcher property name."))
			.String(TEXT("delegateKind"), TEXT("single, multicast, or event_dispatcher for authored delegate variables."))
			.String(TEXT("targetObject"), TEXT("Loaded UObject path receiving a delegate callback."))
			.String(TEXT("functionName"), TEXT("Function name used for interface or delegate operations."))
			.String(TEXT("interfacePath"), TEXT("Blueprint Interface asset path or interface class path."))
			.String(TEXT("interfaceClass"), TEXT("Interface class path or name."))
			.String(TEXT("interfaceFunction"), TEXT("Interface function name."))
			.String(TEXT("interfaceFunctionName"), TEXT("Alias for interfaceFunction."))
			.FreeformObject(TEXT("parameterValues"), TEXT("JSON values for reflected function or delegate parameters."))
			.Bool(TEXT("saveAsset"), TEXT("Save modified Blueprint assets; defaults to true."))
			.Required({TEXT("action")})
			.Build();
	}
};

MCP_REGISTER_TOOL(FMcpTool_SystemControl);
