// McpTool_ManageAsset.cpp — manage_asset tool definition (114 actions)

#include "McpVersionCompatibility.h"
#include "MCP/McpToolDefinition.h"
#include "MCP/McpToolRegistry.h"
#include "MCP/McpSchemaBuilder.h"
#include "MCP/McpConsolidatedActionRouting.h"

class FMcpTool_ManageAsset : public FMcpToolDefinition
{
public:
	FString GetName() const override { return TEXT("manage_asset"); }

	FString GetDescription() const override
	{
		return TEXT("Create, import, duplicate, rename, delete assets. "
			"Edit Material graphs and instances, physical materials, and physics surfaces. Analyze dependencies.");
	}

	FString GetCategory() const override { return TEXT("core"); }

	TSharedPtr<FJsonObject> BuildInputSchema() const override
	{
		return FMcpSchemaBuilder()
			.StringEnum(TEXT("action"), McpConsolidatedActions::ManageAsset(),
				TEXT("Action to perform"))
			.String(TEXT("assetPath"), TEXT("Asset path (e.g., /Game/Path/Asset)."))
			.String(TEXT("name"), TEXT("Asset name."))
			.String(TEXT("path"), TEXT("Asset package path."))
			.String(TEXT("rowStructPath"), TEXT("FTableRowBase-derived struct path for DataTables."))
			.String(TEXT("rowName"), TEXT("DataTable or CurveTable row name."))
			.FreeformObject(TEXT("properties"), TEXT("Reflected DataTable row properties."))
			.ArrayOfObjects(TEXT("keys"), TEXT("CurveTable keys with time/value and optional interpolation/tangent fields."))
			.String(TEXT("csv"), TEXT("CurveTable CSV payload."))
			.String(TEXT("directory"), TEXT("Path to a directory."))
			.Array(TEXT("classNames"), TEXT(""))
			.Array(TEXT("packagePaths"), TEXT(""))
			.Bool(TEXT("recursivePaths"), TEXT(""))
			.Bool(TEXT("recursiveClasses"), TEXT(""))
			.Number(TEXT("limit"), TEXT(""))
			.Number(TEXT("offset"), TEXT(""))
			.String(TEXT("sourcePath"), TEXT("Source path for import/move/copy."))
			.String(TEXT("destinationPath"), TEXT("Destination path for move/copy."))
			.Array(TEXT("assetPaths"), TEXT(""))
			.Number(TEXT("lodCount"), TEXT(""))
			.FreeformObject(TEXT("reductionSettings"), TEXT(""))
			.String(TEXT("nodeName"), TEXT("Name identifier."))
			.String(TEXT("eventName"), TEXT("Name of the event."))
			.String(TEXT("memberClass"), TEXT(""))
			.Number(TEXT("posX"), TEXT(""))
			.Number(TEXT("posY"), TEXT(""))
			.String(TEXT("newName"), TEXT("New name for renaming."))
			.Bool(TEXT("overwrite"), TEXT("Overwrite if the asset/file already exists."))
			.Bool(TEXT("save"), TEXT("Save the asset(s) after the operation."))
			.Bool(TEXT("async"), TEXT("Return a managed asyncId for material/shader compilation completion."))
			.Number(TEXT("timeoutMs"), TEXT("Maximum wait time for asynchronous material compilation."))
			.Bool(TEXT("requireClean"), TEXT("Require the loaded package to be clean after persistence verification."))
			.Bool(TEXT("verifyReload"), TEXT("Unload and reload the asset to verify persistence across an editor reload cycle."))
			.Bool(TEXT("fixupRedirectors"), TEXT(""))
			.String(TEXT("directoryPath"), TEXT("Path to a directory."))
			.String(TEXT("name"), TEXT("Name identifier."))
			.String(TEXT("path"), TEXT("Path to a directory."))
			.String(TEXT("parentMaterial"), TEXT("Material asset path."))
			.FreeformObject(TEXT("parameters"), TEXT(""))
			.Number(TEXT("width"), TEXT(""))
			.Number(TEXT("height"), TEXT(""))
			.String(TEXT("format"), TEXT(""))
			.String(TEXT("mediaUrl"), TEXT("Media file path or stream URL."))
			.StringEnum(TEXT("mediaType"), { TEXT("file"), TEXT("stream") }, TEXT("Media source type."))
			.String(TEXT("mediaPlayerPath"), TEXT("Media player asset path."))
			.String(TEXT("mediaSourcePath"), TEXT("Media source asset path."))
			.String(TEXT("primaryAssetType"), TEXT("Primary Asset type name."))
			.String(TEXT("primaryAssetId"), TEXT("Primary Asset identifier (Type:Name)."))
			.String(TEXT("meshPath"), TEXT("Mesh asset path."))
			.String(TEXT("tag"), TEXT("Name of the tag."))
			.FreeformObject(TEXT("metadata"), TEXT(""))
			.String(TEXT("viewType"), TEXT("Content Browser view type: list, tile, or column."))
			.String(TEXT("thumbnailSize"), TEXT("Content Browser thumbnail size."))
			.String(TEXT("instanceName"), TEXT("Content Browser instance name."))
			.Bool(TEXT("saveConfig"), TEXT("Persist Content Browser settings."))
			.Bool(TEXT("showEngineContent"), TEXT("Show Engine content."))
			.Bool(TEXT("showPluginContent"), TEXT("Show plugin content."))
			.Bool(TEXT("showDeveloperContent"), TEXT("Show developer content."))
			.Bool(TEXT("showFolders"), TEXT("Show folders in the asset view."))
			.Bool(TEXT("showEmptyFolders"), TEXT("Show empty folders."))
			.Bool(TEXT("showCppFolders"), TEXT("Show C++ folders."))
			.Bool(TEXT("showLocalizedContent"), TEXT("Show localized content."))
			.Bool(TEXT("showFavorites"), TEXT("Show favorite folders/assets."))
			.Bool(TEXT("searchAssetPaths"), TEXT("Search asset paths."))
			.Bool(TEXT("searchClasses"), TEXT("Search asset class names."))
			.Bool(TEXT("searchCollections"), TEXT("Search collection names."))
			.Bool(TEXT("filterRecursively"), TEXT("Filter folders recursively."))
			.Bool(TEXT("sourcesExpanded"), TEXT("Expand the sources panel."))
			.String(TEXT("contentBrowserPath"), TEXT("Content Browser path."))
			.String(TEXT("collectionName"), TEXT("Collection name."))
			.String(TEXT("collectionShareType"), TEXT("Collection share type: local, private, or shared."))
			.String(TEXT("collectionStorageMode"), TEXT("Collection storage mode: static or dynamic."))
			.FreeformObject(TEXT("color"), TEXT("Folder color as {r, g, b, a}, normalized 0-1."))
			.Number(TEXT("r"), TEXT("Color red channel."))
			.Number(TEXT("g"), TEXT("Color green channel."))
			.Number(TEXT("b"), TEXT("Color blue channel."))
			.Number(TEXT("a"), TEXT("Color alpha channel."))
			.Bool(TEXT("focusContentBrowser"), TEXT("Focus the Content Browser after sync."))
			.Bool(TEXT("allowLockedBrowser"), TEXT("Allow syncing a locked Content Browser."))
			.Bool(TEXT("newBrowser"), TEXT("Spawn a new browser for sync operations."))
			.String(TEXT("graphName"), TEXT("Name of the graph."))
			.String(TEXT("nodeType"), TEXT(""))
			.String(TEXT("nodeId"), TEXT("ID of the node."))
			.String(TEXT("sourceNodeId"), TEXT("ID of the source node."))
			.String(TEXT("targetNodeId"), TEXT("ID of the target node."))
			.String(TEXT("inputName"), TEXT("Name of the pin."))
			.String(TEXT("fromNodeId"), TEXT("ID of the source node."))
			.String(TEXT("fromPin"), TEXT("Name of the source pin."))
			.String(TEXT("toNodeId"), TEXT("ID of the target node."))
			.String(TEXT("toPin"), TEXT("Name of the target pin."))
			.String(TEXT("parameterName"), TEXT("Name of the parameter."))
			.FreeformObject(TEXT("value"), TEXT("Generic value (any type)."))
			.Number(TEXT("x"), TEXT(""))
			.Number(TEXT("y"), TEXT(""))
			.String(TEXT("comment"), TEXT(""))
			.String(TEXT("parentNodeId"), TEXT("ID of the node."))
			.String(TEXT("childNodeId"), TEXT("ID of the node."))
			.Number(TEXT("maxDepth"), TEXT(""))
			.String(TEXT("prefix"), TEXT(""))
			.String(TEXT("suffix"), TEXT(""))
			.String(TEXT("searchText"), TEXT(""))
			.String(TEXT("replaceText"), TEXT(""))
			.Array(TEXT("paths"), TEXT(""))
			.String(TEXT("description"), TEXT(""))
			.Bool(TEXT("checkoutFiles"), TEXT(""))
			.Bool(TEXT("showConfirmation"), TEXT(""))
			.String(TEXT("pinName"), TEXT("Name of the pin."))
			.String(TEXT("desc"), TEXT(""))
			.String(TEXT("materialPath"), TEXT("Material asset path."))
			.String(TEXT("physicalMaterialPath"), TEXT("Physical material asset path."))
			.String(TEXT("actorName"), TEXT("Actor to receive or inspect a physical material override."))
			.String(TEXT("componentName"), TEXT("Optional primitive component name."))
			.Number(TEXT("friction"), TEXT("Dynamic friction coefficient."))
			.Number(TEXT("staticFriction"), TEXT("Static friction coefficient."))
			.Number(TEXT("restitution"), TEXT("Restitution/bounciness from 0 to 1."))
			.Number(TEXT("density"), TEXT("Physical material density in g/cm3."))
			.String(TEXT("surfaceType"), TEXT("SurfaceType index/name."))
			.String(TEXT("surfaceName"), TEXT("Project physical surface display name."))
			.String(TEXT("frictionCombineMode"), TEXT("average, min, multiply, or max."))
			.String(TEXT("restitutionCombineMode"), TEXT("average, min, multiply, or max."))
			.Bool(TEXT("overrideFrictionCombineMode"), TEXT("Override project friction combine mode."))
			.Bool(TEXT("overrideRestitutionCombineMode"), TEXT("Override project restitution combine mode."))
			.String(TEXT("texturePath"), TEXT("Texture asset path."))
			.String(TEXT("tileSetPath"), TEXT("Optional PaperTileSet asset path for a new tile map."))
			.Number(TEXT("tileWidth"), TEXT("PaperTileSet tile width in pixels."))
			.Number(TEXT("tileHeight"), TEXT("PaperTileSet tile height in pixels."))
			.Number(TEXT("width"), TEXT("Tile-map region width in cells."))
			.Number(TEXT("height"), TEXT("Tile-map region height in cells."))
			.Bool(TEXT("rebuildCollision"), TEXT("Rebuild PaperTileMap collision after cell edits."))
			.Number(TEXT("spacingX"), TEXT("PaperTileSet horizontal tile spacing in pixels."))
			.Number(TEXT("spacingY"), TEXT("PaperTileSet vertical tile spacing in pixels."))
			.Number(TEXT("marginLeft"), TEXT("PaperTileSet left margin in pixels."))
			.Number(TEXT("marginTop"), TEXT("PaperTileSet top margin in pixels."))
			.Number(TEXT("marginRight"), TEXT("PaperTileSet right margin in pixels."))
			.Number(TEXT("marginBottom"), TEXT("PaperTileSet bottom margin in pixels."))
			.Number(TEXT("drawingOffsetX"), TEXT("PaperTileSet drawing offset X in pixels."))
			.Number(TEXT("drawingOffsetY"), TEXT("PaperTileSet drawing offset Y in pixels."))
			.String(TEXT("tileUserData"), TEXT("PaperTileSet per-tile user-data name; empty clears it."))
			.FreeformObject(TEXT("backgroundColor"), TEXT("PaperTileSet viewer background color as {r,g,b,a}."))
			.Number(TEXT("textureU"), TEXT("PaperTileSet texture-space U coordinate in pixels."))
			.Number(TEXT("textureV"), TEXT("PaperTileSet texture-space V coordinate in pixels."))
			.Bool(TEXT("roundUp"), TEXT("Round up during PaperTileSet texture-to-tile conversion."))
			.FreeformObject(TEXT("layerGridColor"), TEXT("UPaperTileMap layer grid color as {r,g,b,a}."))
			.FreeformObject(TEXT("layerColor"), TEXT("UPaperTileLayer color multiplier as {r,g,b,a}."))
			.Bool(TEXT("layerCollides"), TEXT("Whether the PaperTileLayer generates collision."))
			.Bool(TEXT("overrideCollisionOffset"), TEXT("Whether to use a custom PaperTileLayer collision offset."))
			.Number(TEXT("collisionOffsetOverride"), TEXT("PaperTileLayer collision offset in Unreal units."))
			.Bool(TEXT("overrideCollisionThickness"), TEXT("Whether to use a custom PaperTileLayer collision thickness."))
			.Number(TEXT("collisionThicknessOverride"), TEXT("PaperTileLayer collision thickness in Unreal units."))
			.Bool(TEXT("renderInEditor"), TEXT("Whether the PaperTileLayer renders in the editor."))
			.FreeformObject(TEXT("tileGridColor"), TEXT("UPaperTileMap tile grid color as {r,g,b,a}."))
			.FreeformObject(TEXT("multiTileGridColor"), TEXT("UPaperTileMap multi-tile grid color as {r,g,b,a}."))
			.Number(TEXT("multiTileGridWidth"), TEXT("UPaperTileMap multi-tile grid width in tiles."))
			.Number(TEXT("multiTileGridHeight"), TEXT("UPaperTileMap multi-tile grid height in tiles."))
			.Number(TEXT("multiTileGridOffsetX"), TEXT("UPaperTileMap multi-tile grid X offset in tiles."))
			.Number(TEXT("multiTileGridOffsetY"), TEXT("UPaperTileMap multi-tile grid Y offset in tiles."))
			.Number(TEXT("pixelsPerUnrealUnit"), TEXT("UPaperTileMap pixels per Unreal unit."))
			.Number(TEXT("separationPerLayer"), TEXT("UPaperTileMap Z separation per layer."))
			.Number(TEXT("separationPerTileX"), TEXT("UPaperTileMap Z separation per tile on X."))
			.Number(TEXT("separationPerTileY"), TEXT("UPaperTileMap Z separation per tile on Y."))
			.StringEnum(TEXT("pivotMode"), { TEXT("top_left"), TEXT("top_center"), TEXT("top_right"), TEXT("center_left"), TEXT("center_center"), TEXT("center_right"), TEXT("bottom_left"), TEXT("bottom_center"), TEXT("bottom_right"), TEXT("custom") }, TEXT("PaperSprite pivot mode."))
			.Bool(TEXT("trimmed"), TEXT("Whether the PaperSprite source region is trimmed."))
			.Number(TEXT("sourceOriginX"), TEXT("PaperSprite source-region origin X in pixels."))
			.Number(TEXT("sourceOriginY"), TEXT("PaperSprite source-region origin Y in pixels."))
			.Number(TEXT("sourceWidth"), TEXT("PaperSprite source-region width in pixels."))
			.Number(TEXT("sourceHeight"), TEXT("PaperSprite source-region height in pixels."))
			.Number(TEXT("pivotX"), TEXT("Custom PaperSprite pivot X in texture-space coordinates."))
			.Number(TEXT("pivotY"), TEXT("Custom PaperSprite pivot Y in texture-space coordinates."))
			.Bool(TEXT("rebuildData"), TEXT("Rebuild PaperSprite render and collision data after editing."))
			.Array(TEXT("spritePaths"), TEXT("PaperSprite asset paths used as flipbook keyframes."))
			.Array(TEXT("frameRuns"), TEXT("Optional frame durations for flipbook keyframes."))
			.String(TEXT("spritePath"), TEXT("PaperSprite asset path for a new flipbook keyframe."))
			.Number(TEXT("frameRun"), TEXT("Number of frames to display a keyframe."))
			.Number(TEXT("keyFrameIndex"), TEXT("Optional insertion index for a flipbook keyframe."))
			.Number(TEXT("framesPerSecond"), TEXT("Flipbook nominal playback frame rate."))
			.Bool(TEXT("forceResize"), TEXT("Force PaperTileMap resize when reducing dimensions."))
			.StringEnum(TEXT("collisionDomain"), { TEXT("none"), TEXT("2d"), TEXT("3d") }, TEXT("PaperTileMap collision domain."))
			.Number(TEXT("collisionThickness"), TEXT("PaperTileMap collision extrusion thickness."))
			.Number(TEXT("layerIndex"), TEXT("PaperTileMap layer index."))
			.Number(TEXT("tileX"), TEXT("PaperTileMap cell X coordinate for geometry readback."))
			.Number(TEXT("tileY"), TEXT("PaperTileMap cell Y coordinate for geometry readback."))
			.FreeformObject(TEXT("position"), TEXT("PaperTileMap local-space position as {x,y,z}."))
			.String(TEXT("socketName"), TEXT("PaperSprite socket name."))
			.Number(TEXT("alphaThreshold"), TEXT("PaperSprite alpha threshold for tight texture bounds."))
			.Number(TEXT("flags"), TEXT("Packed PaperTileInfo transform flags (0-7)."))
			.String(TEXT("expressionClass"), TEXT(""))
			.Number(TEXT("coordinateIndex"), TEXT(""))
			.String(TEXT("parameterType"), TEXT(""))
			.ArrayOfObjects(TEXT("nodes"), TEXT(""))
			.Array(TEXT("tags"), TEXT(""))
			.String(TEXT("folderPath"), TEXT("Path to a directory."))
			.String(TEXT("sourceNode"), TEXT("ID of the source node."))
			.String(TEXT("targetNode"), TEXT("ID of the target node."))
			.String(TEXT("outputPin"), TEXT("Name of the source pin."))
			.String(TEXT("inputPin"), TEXT("Name of the target pin."))
			.String(TEXT("type"), TEXT(""))
			.FreeformObject(TEXT("defaultValue"), TEXT("Generic value (any type)."))
			.String(TEXT("expressionIndex"), TEXT("ID of the node."))
			.Number(TEXT("depth"), TEXT("Texture or render target depth."))
			.Bool(TEXT("force"), TEXT("Force the operation."))
			.Bool(TEXT("recursive"), TEXT("Recurse into child paths."))
			.String(TEXT("reportType"), TEXT("Report type."))
			.String(TEXT("pattern"), TEXT("Pattern to match."))
			.String(TEXT("replacement"), TEXT("Replacement string."))
			.String(TEXT("materialDomain"), TEXT("Material domain."))
			.String(TEXT("blendMode"), TEXT("Blend mode."))
			.String(TEXT("shadingModel"), TEXT("Shading model."))
			.String(TEXT("domain"), TEXT("Material domain alias."))
			.Bool(TEXT("twoSided"), TEXT("Enable two-sided rendering."))
			.Number(TEXT("uTiling"), TEXT("U tiling factor."))
			.Number(TEXT("vTiling"), TEXT("V tiling factor."))
			.String(TEXT("operation"), TEXT("Math operation type."))
			.Number(TEXT("constA"), TEXT("Constant A value."))
			.Number(TEXT("constB"), TEXT("Constant B value."))
			.String(TEXT("code"), TEXT("Code or expression."))
			.String(TEXT("outputType"), TEXT("Output type."))
			.ArrayOfObjects(TEXT("inputs"), TEXT("Input definitions."))
			.ArrayOfObjects(TEXT("additionalOutputs"), TEXT("Additional output definitions."))
			.String(TEXT("group"), TEXT("Group name."))
			.String(TEXT("sourcePin"), TEXT("Source pin name."))
			.String(TEXT("targetPin"), TEXT("Target pin name."))
			.String(TEXT("direction"), TEXT("Traversal direction."))
			.Bool(TEXT("downstream"), TEXT("Traverse downstream connections."))
			.String(TEXT("startNodeId"), TEXT("Start node ID."))
			.String(TEXT("endPin"), TEXT("End pin name."))
			.Bool(TEXT("orphansOnly"), TEXT("Only include orphaned nodes."))
			.String(TEXT("functionPath"), TEXT("Material function asset path."))
			.String(TEXT("inputType"), TEXT("Input type."))
			.String(TEXT("instancePath"), TEXT("Material instance asset path."))
			.String(TEXT("layerName"), TEXT("Layer name."))
			.String(TEXT("blendType"), TEXT("Blend type."))
			.ArrayOfObjects(TEXT("layers"), TEXT("Layer configurations."))
			.Array(TEXT("nodeIds"), TEXT("Node IDs."))
			.String(TEXT("sourceTexture"), TEXT("Source texture path."))
			.Number(TEXT("strength"), TEXT("Strength value."))
			.Number(TEXT("scale"), TEXT("Scale value."))
			.Number(TEXT("octaves"), TEXT("Octave count."))
			.StringEnum(TEXT("patternType"), {
				TEXT("Checker"), TEXT("Grid"), TEXT("Brick"),
				TEXT("Tile"), TEXT("Dots"), TEXT("Stripes")
			}, TEXT("Pattern texture type."))
			.FreeformObject(TEXT("primaryColor"), TEXT("Primary pattern color {r, g, b, a}."))
			.FreeformObject(TEXT("secondaryColor"), TEXT("Secondary pattern color {r, g, b, a}."))
			.Number(TEXT("tilesX"), TEXT("Pattern tile count horizontally."))
			.Number(TEXT("tilesY"), TEXT("Pattern tile count vertically."))
			.Number(TEXT("lineWidth"), TEXT("Grid, tile, and brick line width (0-0.5)."))
			.Number(TEXT("brickRatio"), TEXT("Brick width/height ratio."))
			.Number(TEXT("offset"), TEXT("Brick row offset (0-1)."))
			.Number(TEXT("samples"), TEXT("Sample count."))
			.Number(TEXT("newWidth"), TEXT("New width."))
			.Number(TEXT("newHeight"), TEXT("New height."))
			.String(TEXT("filterMethod"), TEXT("Filter method."))
			.Number(TEXT("inBlack"), TEXT("Input black point."))
			.Number(TEXT("inWhite"), TEXT("Input white point."))
			.Number(TEXT("gamma"), TEXT("Gamma value."))
			.ArrayOfObjects(TEXT("curvePoints"), TEXT("Curve control points."))
			.Number(TEXT("amount"), TEXT("Effect amount."))
			.Number(TEXT("radius"), TEXT("Radius value."))
			.String(TEXT("channel"), TEXT("Channel name."))
			.String(TEXT("redTexture"), TEXT("Red channel texture path."))
			.String(TEXT("greenTexture"), TEXT("Green channel texture path."))
			.String(TEXT("blueTexture"), TEXT("Blue channel texture path."))
			.String(TEXT("baseTexture"), TEXT("Base texture path."))
			.String(TEXT("blendTexture"), TEXT("Blend texture path."))
			.Number(TEXT("opacity"), TEXT("Opacity value."))
			.String(TEXT("compressionSettings"), TEXT("Texture compression settings."))
			.String(TEXT("textureGroup"), TEXT("Texture group."))
			.Number(TEXT("lodBias"), TEXT("LOD bias."))
			.Bool(TEXT("virtualTextureStreaming"), TEXT("Enable virtual texture streaming."))
			.Bool(TEXT("neverStream"), TEXT("Never stream this texture."))
			.Number(TEXT("streamingPriority"), TEXT("Streaming priority."))
			.Number(TEXT("speed"), TEXT("Speed value."))
			.Number(TEXT("speedX"), TEXT("X speed value."))
			.Number(TEXT("speedY"), TEXT("Y speed value."))
			.Number(TEXT("levels"), TEXT("Level count."))
			.Required({TEXT("action")})
			.Build();
	}
};

MCP_REGISTER_TOOL(FMcpTool_ManageAsset);
